### ISSUE TITLE
Develop a function to resolve URI references 

### ISSUE THREAD

**Issue by glynos** [cpp-netlib/cpp-netlib#114]
```
network::uri base_uri("http://www.example.com/");
network::uri relative_uri("/relative/path/");
network::uri uri(base_uri.resolve(relative_uri));
assert(uri == "http://www.example.com/relative/path/");
```

**Comment by lockie** [comment]
Hello!
Why did you close this? Supporting relative URLs would be awesome (actually, even `libs/network/test/uri/relative_uri_test.cpp` passing with some relative URL would do).

**Comment by glynos** [comment]
I closed this three years ago, and I can't remember what the issue was (there isn't enough information).

A lot of fixes were applied on the uri repo, and that implementation includes functions to resolve URIs. Does this help you?

**Comment by lockie** [comment]
> Does this help you?

It does indeed, thanks for pointing to right direction.

So I'll have to use the uri library along with cpp-netlib itself?

**Comment by glynos** [comment]
Not in the latest release, I'm afraid.

I am in the process of integrating the URI into cpp-netlib's master branch though.

**Comment by lockie** [comment]
Got it, thanks.
