### ISSUE TITLE
wget example hangs using -std=c++11

### ISSUE THREAD

**Issue by jowi24** [cpp-netlib/cpp-netlib#185]
I compile the simple wget example using cpp-netlib 0.9.4:

```
c++ -I/usr/include/cpp-netlib -o simple_wget simple_wget.cpp \
-lboost_system -lboost_thread -lcppnetlib-client-connections \
-lcppnetlib-uri -lpthread -lssl -lcrypto
```

This works:
    $ ./simple_wget http://www.google.de
Saving to: index.html

However, if I add -std=c++11 to the compiler commandline, simple_wget hangs and does not return to the shell. 

Any idea whats wrong here?

**Comment by Kebs00n** [comment]
The problem is solved here : https://github.com/cpp-netlib/cpp-netlib/issues/493
