### ISSUE TITLE
problems building on Ubuntu 13.04

### ISSUE THREAD

**Issue by nieknooijens** [cpp-netlib/cpp-netlib#246]
hi there

my system is in dutch so I've provided translation using << [translation]
ok this is what I did:

niek@niek-N73SV:~/Bureaublad$ git clone git://github.com/cpp-netlib/cpp-netlib.git
Cloning into 'cpp-netlib'...
remote: Counting objects: 13378, done.
remote: Compressing objects: 100% (7427/7427), done.
remote: Total 13378 (delta 5879), reused 13070 (delta 5617)
Receiving objects: 100% (13378/13378), 6.21 MiB | 1.78 MiB/s, done.
Resolving deltas: 100% (5879/5879), done.
niek@niek-N73SV:~/Bureaublad$ mkdir cpp-netlib-build
niek@niek-N73SV:~/Bureaublad$ cd cpp-netlib
niek@niek-N73SV:~/Bureaublad/cpp-netlib$ cd ../cpp-netlib-build/
niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$ make -DCMAKE_BUILD_TYPE=Debug \

> > ```
> >   -DCMAKE_C_COMPILER=gcc   \
> >   -DCMAKE_CXX_COMPILER=g++ \
> >   ../cpp-netlib
> > ```
> > 
> > bash: ../cpp-netlib: Is een map                                                                   << it's a folder!!
> > niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$ make
> > make: **\* Geen doelen opgegeven en geen makefile gevonden.  Gestopt.   << did not specify target and did not find makefile
> > niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$ 

so in short, it doesn't work, I can retry without the extra cmake commands which will give me this:
niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$ cmake ../cpp-netlib
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   regex
--   date_time
--   filesystem
--   program_options
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1c") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_STD11
-- Performing Test HAVE_STD11 - Success
C++ Compiler ID: GNU
C++ Flags: -std=c++11 -Wall link flags: 
-- CPP-NETLIB options selected:
--   CPP-NETLIB_BUILD_SHARED_LIBS: OFF  (Build cpp-netlib as shared libraries: OFF, ON)
--   CPP-NETLIB_BUILD_SINGLE_LIB:  OFF  (Build cpp-netlib into a single library: OFF, ON)
--   CPP-NETLIB_BUILD_TESTS:       ON   (Build the unit tests: ON, OFF)
--   CPP-NETLIB_BUILD_EXAMPLES:    ON   (Build the examples using cpp-netlib: ON, OFF)
--   CPP-NETLIB_ALWAYS_LOGGING:    OFF  (Allow cpp-netlib to log debug messages even in non-debug mode: ON, OFF)
--   CPP-NETLIB_DISABLE_LOGGING:   OFF  (Disable logging definitely, no logging code will be generated or compiled: ON, OFF)
--   CPP-NETLIB_DISABLE_LIBCXX:    OFF  (Disable using libc++ when building with clang: ON, OFF)
-- CMake build options selected:
CMake Error at CMakeLists.txt:115 (add_subdirectory):
  The source directory

```
/home/niek/Bureaublad/cpp-netlib/deps/gmock
```

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:142 (add_subdirectory):
  The source directory

```
/home/niek/Bureaublad/cpp-netlib/uri
```

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$ make
make: **\* Geen doelen opgegeven en geen makefile gevonden.  Gestopt.
niek@niek-N73SV:~/Bureaublad/cpp-netlib-build$

**Comment by louwers** [comment]
This is not in the getting guide started http://cpp-netlib.org/0.9.2/getting_started.html.

**Comment by nieknooijens** [comment]
this issue is old.... it's now in the debian repo's

**Comment by louwers** [comment]
I will install it through a package manager then, thanks! :+1:
