### ISSUE TITLE
There is no client timeout setting

### ISSUE THREAD

**Issue by eakraly** [cpp-netlib/cpp-netlib#322]
There is no way to set a timeout on client side so that if server cannot handle request or is unavailable then the client would fail fast.

**Comment by paralin** [comment]
I really need a timeout setting somewhere, my app sometimes waits for a good 5 minutes for a response from one particularly shitty HTTP server.

**Comment by deanberris** [comment]
@paralin Have you tried using the latest in 0.11-devel?

**Comment by deanberris** [comment]
No docs yet @paralin -- but yes, when you create the client object you should be able to set the timeout variable.
