### ISSUE TITLE
missing noexcept qualifier

### ISSUE THREAD

**Issue by taojinqiu** [cpp-netlib/cpp-netlib#391]
located in http/src/network/http/v2/client/request.hpp.
The destructor of class string_byte_source should be noexcept because its parent class byte_source has a noexcept destructor. And this will cause a compile issue on Ubuntu 12 with g++ 4.7.3
```c++
  virtual ~string_byte_source() noexcept {}
```

**Comment by glynos** [comment]
No longer applies.
