### ISSUE TITLE
CMakeLists.txt should use ${Boost_SYSTEM_LIBRARY}

### ISSUE THREAD

**Issue by clemahieu** [cpp-netlib/cpp-netlib#407]
cpp-netlib / libs / network / src / CMakeLists.txt

uses

target_link_libraries(cppnetlib-client-connections ${Boost_System_LIBRARY})

which fails at least on OSX, maybe other case-sensitive OSs?  Should be

target_link_libraries(cppnetlib-client-connections ${Boost_SYSTEM_LIBRARY})

**Comment by povilasb** [comment]
I've encountered the same problem: https://github.com/cpp-netlib/cpp-netlib/blob/0.11-devel/libs/network/src/CMakeLists.txt#L48.

I'm using Debian 7 amd64 system, cmake 3.0, boost 1.57.0.

And at least in cmake 3.x the found library names are uppercased, e.g. ${Boost_SYSTEM_LIBRARY}. https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L988-989

I will make pull request later on today :)

**Comment by deanberris** [comment]
I see you've fixed this now, thanks @povilasb!
