### ISSUE TITLE
Unable to compile without OpenSSL

### ISSUE THREAD

**Issue by lyytinen** [cpp-netlib/cpp-netlib#444]
I'm not completely sure but it appears that omitting the `BOOST_NETWORK_ENABLE_HTTPS` macro does not have any affect anymore. You still get an error if you try to compile without OpenSSL:

    error C1083: Cannot open include file: 'openssl/conf.h'

My guess for the reason is this commit https://github.com/cpp-netlib/cpp-netlib/commit/b7488ddb9eb1dc703e31a74afd215fd00627ee3b that added SSL support and included `boost/asio/ssl.hpp` without using the macro.

**Comment by deanberris** [comment]
Thanks @blastbay -- I do think it's a little unfortunate that the project depends on OpenSSL (or that Boost.Asio doesn't have support for other libraries implementing TLS). However, I would be happy to review changes to make the library not explicitly require OpenSSL. If you bring this up in the mailing list and have someone else take on the effort to making it happen, I would very much welcome pull requests to that effect.

Cheers

**Comment by ericmjones** [comment]
SChannel under Windows or another SSL implementation would be great

**Comment by susnux** [comment]
I think this can be closed, it is fixed since commit https://github.com/cpp-netlib/cpp-netlib/commit/716911adfc55a0f61feb434e3dc36adcf7185335
