### ISSUE TITLE
Xcode 6.1 quickly shutdown when activating breakpoint anywhere

### ISSUE THREAD

**Issue by toolbits** [cpp-netlib/cpp-netlib#466]
I use cpp-netlib 0.11.1RC2 on Xcode 6.1 + Yosemite + boost 1.56.0.  
When I use boost::network::uri::uri class and make it's instance, I cannot use Xcode's debugger with breakpoints.  
If there is no breakpoints and breakpoints are deactivated, that code run smoothly.
If a breakpoint is installed anywhere, Xcode's debugger quickly hung-up.

I found where is the problem.
Below code is in boost/network/uri/uri.ipp file:

#if 0
                        // original code
                        ipv6address %= qi::raw
                        [qi::repeat(6)[h16 >> ':'] >> ls32 |
                         "::" >> qi::repeat(5)[h16 >> ':'] >> ls32 |
                         -qi::raw[h16] >> "::" >> qi::repeat(4)[h16 >> ':'] >> ls32 |
                         -qi::raw[h16] >> "::" >> qi::repeat(3)[h16 >> ':'] >> ls32 |
                         -qi::raw[h16] >> "::" >> qi::repeat(2)[h16 >> ':'] >> ls32 |
                         -qi::raw[h16] >> "::" >> h16 >> ':' >> ls32 |
                         -qi::raw[h16] >> "::" >> ls32 | -qi::raw[h16] >> "::" >> h16 |
                         -qi::raw[h16] >> "::" |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >>
                         qi::repeat(3)[h16 >> ':'] >> ls32 |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >>
                         qi::repeat(2)[h16 >> ':'] >> ls32 |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> h16 >>
                         ':' >> ls32 |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                         -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" |
                         -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >>
                         qi::repeat(2)[h16 >> ':'] >> ls32 |
                         -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> h16 >>
                         ':' >> ls32 |
                         -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                         -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                         -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" |
                         -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> h16 >>
                         ':' >> ls32 |
                         -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                         -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                         -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" |
                         -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                         -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                         -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" |
                         -qi::raw[qi::repeat(5)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                         -qi::raw[qi::repeat(5)[(h16 >> ':')] >> h16] >> "::" |
                         -qi::raw[qi::repeat(6)[(h16 >> ':')] >> h16] >> "::"];
#else
                        // fixed for Xcode 6.1 + boost 1.56.0
                        qi::rule&lt;const_iterator, string_type()> a;
                        qi::rule&lt;const_iterator, string_type()> b;
                        qi::rule&lt;const_iterator, string_type()> c;
                        qi::rule&lt;const_iterator, string_type()> d;
                        a %= qi::repeat(6)[h16 >> ':'] >> ls32 |
                        "::" >> qi::repeat(5)[h16 >> ':'] >> ls32 |
                        -qi::raw[h16] >> "::" >> qi::repeat(4)[h16 >> ':'] >> ls32 |
                        -qi::raw[h16] >> "::" >> qi::repeat(3)[h16 >> ':'] >> ls32 |
                        -qi::raw[h16] >> "::" >> qi::repeat(2)[h16 >> ':'] >> ls32 |
                        -qi::raw[h16] >> "::" >> h16 >> ':' >> ls32 |
                        -qi::raw[h16] >> "::" >> ls32 | -qi::raw[h16] >> "::" >> h16 |
                        -qi::raw[h16] >> "::" |
                        -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> qi::repeat(3)[h16 >> ':'] >> ls32 |
                        -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> qi::repeat(2)[h16 >> ':'] >> ls32 |
                        -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> h16 >> ':' >> ls32;
                        b %= -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                        -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                        -qi::raw[qi::repeat(1)[(h16 >> ':')] >> h16] >> "::" |
                        -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> qi::repeat(2)[h16 >> ':'] >> ls32 |
                        -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> h16 >> ':' >> ls32;
                        c %= -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                        -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                        -qi::raw[qi::repeat(2)[(h16 >> ':')] >> h16] >> "::" |
                        -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> h16 >> ':' >> ls32;
                        d %= -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                        -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                        -qi::raw[qi::repeat(3)[(h16 >> ':')] >> h16] >> "::" |
                        -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" >> ls32 |
                        -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                        -qi::raw[qi::repeat(4)[(h16 >> ':')] >> h16] >> "::" |
                        -qi::raw[qi::repeat(5)[(h16 >> ':')] >> h16] >> "::" >> h16 |
                        -qi::raw[qi::repeat(5)[(h16 >> ':')] >> h16] >> "::" |
                        -qi::raw[qi::repeat(6)[(h16 >> ':')] >> h16] >> "::";
                        ipv6address %= qi::raw[a | b | c | d];
#endif

When I use original code, Xcode hung up. If fixed version is used, Xcode runs well.

**Comment by stari4ek** [comment]
We have same issue with Xcode 6.1.1 and 6.2, boost 1.57, latest cpp-netlib/uri (55ec3cd78918c42dfb874e01c9745b4daf51091b)

**Comment by Falven** [comment]
Having the same issue with Xcode Version 6.2 (6C131e), boost 1.57 and head cpp-netlib.

**Comment by deanberris** [comment]
I don't know about @glynos' availability -- so it looks like this is could be fixed with changing the way we define the grammar. @toolbits do you have time to send a pull request? I'd love to review that and merge it to both the URI library and 0.11-devel. I suspect there's some things we can do to optimize our usage of Spirit here, and that we haven't been doing the "best practices" when it comes to complicated grammars.

**Comment by toolbits** [comment]
Hi, I made a pull request for this issue. I don't know about boost qi so much. Please review carefully about my modification.

**Comment by deanberris** [comment]
I think the latest in 0.11-devel should have fixed this. Can you see whether that's true @toolbits? Closing for now, assuming the parser break-up would have dealt with this already.
