### ISSUE TITLE
Memory corruption in http::client::post

### ISSUE THREAD

**Issue by urbanyoung** [cpp-netlib/cpp-netlib#482]
I'm using the latest stable release (0.11.1-final) downloaded from http://cpp-netlib.org/ and have noticed that references to a local object are being stored for certain post requests. I apologize in advance for the poor quality of this report, but the code I downloaded from your website doesn't seem to match the repo. For instance, in the downloaded code the problem file is boost/network/protocol/http/client/facade.hpp and the closest I can find in the repo is  https://github.com/cpp-netlib/cpp-netlib/blob/master/http/src/network/protocol/http/client/facade.ipp#L46

Regardless, they both have the same issue.

The linked function operates on a local copy of the request object which then gets passed, by reference, to request_skeleton. Eventually host() is called on this object, and the result is stored. Later on, when the newly created thread tries to access the stored data, it is no longer valid because the local request object has long since been destroyed. 

I don't have a proposed fixed because I'm not familiar enough with the library, but in my own code I simply changed post to accept a reference, and ensure the request remains valid for the duration of the post.

Hope that makes sense.

**Comment by deanberris** [comment]
You're looking at the wrong version of the file -- the link you have is to the master branch, which is not where 0.11-devel comes from.

That said, I think there's a potential for this to actually be a problem. I'm going to see if I can actually fix this in 0.11.2 (or whether someone else can).

**Comment by joshuanapoli** [comment]
The specific problem is that [`basic_client_facade::post`](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/client/facade.hpp#L55) takes the `request` argument by value. A reference to the new `request` is passed through:
1. [`async_client<...>::request_skeleton`](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/client/async_impl.hpp#L75).
2. [`async_connection_policy<...>::connection_impl::send_request`](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/policies/async_connection.hpp#L54)
3. [`http_async_connection<...>::start`](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/client/connection/async_normal.hpp#L87)

In `http_async_connection<...>::start`, the result of `host(request)` is [bound to a function and attached to a strand](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/client/connection/async_normal.hpp#L100). The result type of `host(request)` is a [`host_wrapper`](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/message/wrappers/host.hpp#L20). This has reference semantics.

Unfortunately, the referenced request goes out of scope when `basic_client_facade::post` returns. This leaves a dangling reference. The dangling reference eventually leads to undefined behavior when it is used in the processing of callbacks for the connection and message exchange.

The [put request](https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.1-final/boost/network/protocol/http/client/facade.hpp#L106) has the same flaw.

Also, the documentation/tutorial should probably make it more clear that the application is responsible for ensuring the lifetime of these values lasts until the request has terminated. Managing this lifetime takes some care when using the client interface in an asynchronous pattern.

**Comment by deanberris** [comment]
@joshuanapoli Wow -- that's a great analysis! Do you think you can fix this?

**Comment by joshuanapoli** [comment]
I think that the fix is to simply convert the `host_wrapper` to a string before binding. #506 fixes the 0.11 branch. I had a reproducible crash in my application that is fixed by this change.

**Comment by eco** [comment]
I'm surprised a new release hasn't been made for this issue. Not being able to `post` or `put` without crashing in an http library seems like the type of thing that would warrant a hotfix.

I switched to the 0.11-devel branch and it cleared up for me.
