### ISSUE TITLE
how to set the install path of cpp-netlib?

### ISSUE THREAD

**Issue by tianchao-haohan** [cpp-netlib/cpp-netlib#486]
The default install path is /usr/local. How to change the install path to /usr?
The message below is the details of cmake output, it seems that the install path was config successfully firstly, but changed in the next loop:

cmake ../cpp-netlib-0.11.0-final/ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ 
INSTALL_CMAKE_DIR /usr/lib/CMake/cppnetlib
CMAKE_INSTALL_PREFIX /usr                       (####marked####)
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   regex
--   date_time
--   thread
--   filesystem
--   program_options
--   chrono
--   atomic
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
INSTALL_CMAKE_DIR /usr/lib/CMake/cppnetlib
CMAKE_INSTALL_FULL_INCLUDEDIR /usr/include
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= clang
CMAKE_CXX_COMPILER= clang++

-- The C compiler identification is Clang 3.4.2
-- The CXX compiler identification is Clang 3.4.2
-- Check for working C compiler: /home/hanh/workspace/tools/clang/clang+llvm-3.4.2-x86_64-fedora20/bin/clang
-- Check for working C compiler: /home/hanh/workspace/tools/clang/clang+llvm-3.4.2-x86_64-fedora20/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/hanh/workspace/tools/clang/clang+llvm-3.4.2-x86_64-fedora20/bin/clang++
-- Check for working CXX compiler: /home/hanh/workspace/tools/clang/clang+llvm-3.4.2-x86_64-fedora20/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
INSTALL_CMAKE_DIR /usr/local/lib/CMake/cppnetlib
CMAKE_INSTALL_PREFIX /usr/local                              (####marked####)
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   regex
--   date_time
--   thread
--   filesystem
--   program_options
--   chrono
--   atomic

**Comment by deanberris** [comment]
Huh, that's interesting. @infinity0 -- have you ever tried doing anything here?

**Comment by deanberris** [comment]
Is this still a problem in 0.11.2 @tianchao-haohan?
