### ISSUE TITLE
Parsing empty query parameters

### ISSUE THREAD

**Issue by FranciscoMoya** [cpp-netlib/cpp-netlib#499]
Please, consider applying the following patch to allow empty values in a key/value query string. There are many situations in which they can occur.

Regards,
F. Moya

<pre>
diff --git a/boost/network/uri/accessors.hpp b/boost/network/uri/accessors.hpp
index c050458..5248b34 100644
--- a/boost/network/uri/accessors.hpp
+++ b/boost/network/uri/accessors.hpp
@@ -27,7 +27,7 @@ struct key_value_sequence : spirit::qi::grammar<uri::const_iterator, Map()> {
     pair = key >> -('=' >> value);
     key =
         spirit::qi::char_("a-zA-Z_") >> *spirit::qi::char_("-+.~a-zA-Z_0-9/%");
-    value = +spirit::qi::char_("-+.~a-zA-Z_0-9/%");
+    value = *spirit::qi::char_("-+.~a-zA-Z_0-9/%");
   }
 
   spirit::qi::rule<uri::const_iterator, Map()> query;
</pre>

**Comment by leecoder** [comment]
+1

**Comment by glynos** [comment]
Sorry for the slow response.

Instead of requesting a patch, could you make a pull request instead? It
will be much easier for us to track. Additional unit tests covering this
scenario would also be appreciated.

Regards,
Glyn

**Comment by deanberris** [comment]
I echo @glynos here. Please add a pull request so that we can attribute the fix appropriately. If @FranciscoMoya can do it, I'd love to merge it. If not, @leecoder do you mind making that pull request?

**Comment by leecoder** [comment]
Ok~ I'll take it.
This reply was late because I've moved to new office in Tokyo.
