### ISSUE TITLE
support for pkg-config

### ISSUE THREAD

**Issue by bstarynk** [cpp-netlib/cpp-netlib#510]
It would be nice, for free software using `cpp-netlib`  on Linux in C++11 which is compiled with only `make` (and without using `cmake`), to have some support for [pkg-config](http://www.freedesktop.org/wiki/Software/pkg-config/). Then a GNU `makefile` for such projects might be as simple as [this example](http://stackoverflow.com/a/20146082/841108).

Unfortunately I am not familiar enough with `cpp-netlib` or with `cmake` to propose a patch (probably some `cpp-netlib.pc.in` template with some build rule to instanciate it with the actual destination directory used by `cmake` in its `make install` step).

**Comment by deanberris** [comment]
I agree completely.

@infinity0 might know a little more about this, as he's I believe the maintainer of the Debian package.

**Comment by infinity0** [comment]
Unfortunately I know next to nothing about pkg-config. I only maintain the Debian package; pkg-config support is an upstream issue, and these days I don't have enough time to go that far into cpp-netlib.

**Comment by bstarynk** [comment]
` pkg-config`  is not at all Debian specific. I guess that most Linux distributions would package it (at least optionally), since it is useful for GTK and many desktop related software, and many system utilities.

A patch to support `pkg-config`  should go upstream (inside the core `cpp-netlib`), within some `CMake*`  files. I know nearly nothing about `cmake`  (except that I am barely able to use it to compile `cmake` -based free software) so I am not able to propose a patch, but it should got here, into the master `ccp-netlib`  git repository

**Comment by deanberris** [comment]
I agree -- but I don't know much CMake aside from the standard intro-level documentation on it too. :frowning:
