### ISSUE TITLE
Can't build cpp-netlib 

### ISSUE THREAD

**Issue by GardenStateNinja** [cpp-netlib/cpp-netlib#512]
cpp-netlib: 0.11.1
OS: Centos6.6
gcc/g++: 4.9.2
boost: 1.57.0

CMake command: 
> cmake -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_C_COMPILER=/usr/local/gcc/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc/bin/g++ -DBOOST_ROOT=/usr/local/boost ..
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   regex
--   date_time
--   thread
--   filesystem
--   program_options
--   chrono
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final/build

So far, everything is OK. All necessary files generated. 

When make, got errors. 
[  8%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o
cd /home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final/build/libs/network/src && /usr/local/gcc/bin/g++   -DBOOST_NETWORK_DEBUG -DBOOST_NETWORK_ENABLE_HTTPS -Wall -g -I/usr/local/boost/include -I/home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final    -o CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o -c /home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final/libs/network/src/uri/uri.cpp
g++: internal compiler error: Killed (program cc1plus)
0x409edc execute
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:2854
0x40a2a4 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:4658
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
0x40b119 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5312
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
0x40b119 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5312
0x40ae83 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5427
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
0x40b119 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5312
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
0x40b119 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5312
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
0x40b119 do_spec_1
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5312
0x40cb66 process_brace_body
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5941
0x40cb66 handle_braces
        /home/vagrant/install/objdir/../gcc-4.9.2/gcc/gcc.c:5855
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [libs/network/src/CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o] Error 4
make[2]: Leaving directory `/home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final/build'
make[1]: *** [libs/network/src/CMakeFiles/cppnetlib-uri.dir/all] Error 2
make[1]: Leaving directory `/home/vagrant/install/cpp-netlib/cpp-netlib-0.11.1-final/build'
make: *** [all] Error 2

**Comment by deanberris** [comment]
This is the template depth issue. I think there's a special flag that needs to be set in CMake for some compilers so it doesn't blow up when compiling code that's heavily dependent on Boost.Spirit.
