### ISSUE TITLE
simple widget can not run

### ISSUE THREAD

**Issue by linkt** [cpp-netlib/cpp-netlib#513]
I use the 11.1 in vs2013 ,but it can`t run normally,the response is empty
![image](https://cloud.githubusercontent.com/assets/7455401/6979897/ae51d20a-da1c-11e4-8436-a542946c7f77.png)

**Comment by glynos** [comment]
I'm sorry, we can't do much with this information. Could you provide more details?

**Comment by linkt** [comment]
#include <boost/network/protocol/http/client.hpp>
#include <boost/network/uri.hpp>
#include <string>
#include <fstream>
#include <iostream>

namespace http = boost::network::http;
namespace uri = boost::network::uri;

namespace {
	std::string get_filename(const uri::uri &url) {
		std::string path = uri::path(url);
		std::size_t index = path.find_last_of('/');
		std::string filename = path.substr(index + 1);
		return filename.empty() ? "index.html" : filename;
	}
} // namespace

int main(int argc, char *argv[]) {
	
		http::client client;
		http::client::request request("http://www.boost.org/");
		http::client::response response = client.get(request);

		std::string filename = get_filename(request.uri());
		std::cout << "Saving to: " << filename << std::endl;
		std::ofstream ofs(filename.c_str());
		ofs << static_cast<std::string>(body(response)) << std::endl;

	return 0;
}
I use the codes complie ,and set the breakpoint ,I found that client.get()  return nothing .the response is empty;

**Comment by linkt** [comment]
i found that there are not http or tcp packet when I use the wirshark

**Comment by linkt** [comment]
The examples(The Hello-World-Client and The Hello-World -Server) i copyed from the official website can't work normally even when i use the local area network.What makes me so puzzled is both of them didn't have any communication.
PS,Win7+boost-1.55.0+vs2013

**Comment by deanberris** [comment]
What's happening here is simple:

  - We don't actually make any requests synchronously. The response object will be empty, until the client's thread has run all the asynchronous operations it needs to run.
  - If you set the breakpoint at 'return 0' then you'd probably find something's already happened by then, and that the response object is no longer empty.

The documentation has pointed out that the default implementation of the client has switched to the asynchronous version from older versions.
