### ISSUE TITLE
Windows VS compilation problems

### ISSUE THREAD

**Issue by Falven** [cpp-netlib/cpp-netlib#526]
Windows 8.1 x64
Latest stable source 0.11.1 final
CMake 3.2.2 Windows GUI.

I have Boost 1.58.0 properly built:

`bootstrap`
`b2 link=static,shared address-model=64 threading=single,multi`

For both static and shared libraries.

When building cpp-netlib static library:
All Default configuration values.
Configuration and Generation works.
Open the solution from Visual Studio 2013 with Admin Privileges.
right click ALL_BUILD -> Build.
Output: 30 succeeded, 3 failed
error C1128: number of sections exceeded object file format limit : compile with /bigobj client_get_different_port_test.cpp
error C1128: number of sections exceeded object file format limit : compile with /bigobj client_get_test.cpp
error C1128: number of sections exceeded object file format limit : compile with /bigobj	client_get_timeout_test.cpp

Otherwise builds fine without tests configuration value selected for static library.

When building cpp-netlib shared library:
All Default configuration values except build tests unchecked and build shared libs checked.
Configuration and Generation works.
Open the solution from Visual Studio 2013 with Admin Privileges.
right click ALL_BUILD -> Build.
Output: 4 succeeded, 10 failed
error LNK1104: cannot open file 'libboost_thread-vc120-mt-gd-1_58.lib'
error LNK1104: cannot open file 'libboost_system-vc120-mt-gd-1_58.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'
error LNK1104: cannot open file '..\src\Debug\cppnetlib-uri.lib'

Both of those libraries are available in the Boost stage directory.
My guess is for some reason cpp-netlib requires 32 bit versions of those or something?
Tried compiling all boost libs as 32 bit and cpp-netlib complained it requires 64 bit.

**Comment by deanberris** [comment]
Hi Francisco, can you try the latest from the 0.11-devel branch to see if this has already been fixed?

**Comment by deanberris** [comment]
So this one seems to be a /bigobj flag missing in the build. This I think is already fixed in the master branch, but if it's not please re-open the issue.
