### ISSUE TITLE
hello_world_client can't commuicate with the hello_world_async_server_with_work_queue

### ISSUE THREAD

**Issue by linkt** [cpp-netlib/cpp-netlib#536]
hello,I used the hello_word_client to communicate with the hello_world_async_server_with_work_queue,but can't get response,the errors are: 

1.C:\Users\Administrator\Desktop>hello_world_client.exe http://127.0.0.1:8000
[DEBUG C:\boost_1_55_0\boost/network/protocol/http/client/connection/async_proto
col_handler.hpp:119]: [parser:1] buffer contents: "Hello, 127.0.0.1:2460:52685!"
Invalid Version Part.

2.I use the client to post a string to server .I find that the the body of request that the server recieved is empty, 
 what' s matter?
ps： if I use the hello_world_server it is OK.I use the vs2013+cpp-netlib 1.1+boost1.55

**Comment by deanberris** [comment]
Interesting. What version of the library are you using? 0.11.1? I think this is a bug in the example, but I don't have time to have a look at the async example. Do you mind trying to debug that particular implementation if you have time?

**Comment by WilliamTambellini** [comment]
Hello all
 I got the same exception/crash "Invalid Version Part" when using:
- netlib 0.11.1, boost 1.57, gcc5
- network/example/http/ssl async_server example
- simple http client get such as:
```
    boost::network::http::client::request request("https://localhost:8080");
    boost::network::http::client::response response = client.get(request);
    std::cout << status_message(response) << std::endl;
    std::cout << body(response) << std::endl; // expecting "Hello World" 
```
Is it supposed to work ?
Cheers

**Comment by WilliamTambellini** [comment]
ok, it looks like the async server has to set headers in the handler in order for the async client to work: 
example: 
server::response_header headers[] = { {"Connection","close"} ,{"Content-Type", "text/plain"} };
connection->set_headers(boost::make_iterator_range(headers, headers+2));
Dont know why curl is doing well whatever the server is doing: with or without setting the headers.

**Comment by deanberris** [comment]
Yes, you need to set the headers -- otherwise cpp-netlib will not know when/how to interpret the response.

Can you send a pull request to the 0.11-devel branch @WilliamTambellini to fix this?

**Comment by ytong3** [comment]
Same thing happened when I used the http_client to make ssl connection with ssl_server. 

The Invalid Version Part went away after setting the headers in ssl_server
Something like

    struct handler {
         void operator()(server::request const& req,
                              const server::connection_ptr& conn) {
          conn->set_status(server::connection::ok);
          server::response_header headers[]={{"Connection","close"},{"Content-Type","text/plain"}};
          conn->set_headers(boost::make_iterator_range(headers,headers+2));
          conn->write(std::string("Hello World!!\n"));
         }
    };
