### ISSUE TITLE
Error linking 'boost::network::uri::detail::parse' on OSX

### ISSUE THREAD

**Issue by FlexTheCat** [cpp-netlib/cpp-netlib#538]
Hi guys,

we changed to cpp-netlib 0.11.1 (from 0.9.4) on OSX. Boost (1.58) and cpp-netlib compilation works like a charm.
When linking our own code (with the same arguments as with 0.9.4) we get the following error:

Undefined symbols for architecture x86_64:
  "boost::network::uri::detail::parse(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::network::uri::detail::uri_parts<__gnu_cxx::__normal_iterator<char const*, std::string> >&)", referenced from:
      boost::network::uri::uri::parse() in XYZ.o
ld: symbol(s) not found for architecture x86_64

Doing
nm libs/network/src/libcppnetlib-uri.a| c++filt | grep -i boost::network::uri::detail::parse :
0000000000000000 T boost::network::uri::detail::parse(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>, boost::network::uri::detail::uri_parts<std::__1::__wrap_iter<char const*> >&)

So the symbol is there. The many zeros seem wrong.With 0.9.4 we get it different. I assume it's something about the way we build 0.11.1? Anyone else running into this/similar problems?

- OSX 10.7.5
- 10.7 sdk
- xcode 4.6.2 
- clang++ --version
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2

Thanks for any hint/help!

**Comment by deanberris** [comment]
Can you provide the steps you use to build the library? I work primarily on OS X with Clang as well, so I can try and reproduce this myself.

**Comment by FlexTheCat** [comment]
Thanks for your quick reaction.
Pretty simple steps:
unzip cpp-netlib-0.11.1-final.zip and cd into it
export BOOST_ROOT=$MYBOOSTROOTDIR
cmake -DCMAKE_CXX_FLAGS="-arch x86_64"
cd libs/network/src/
make

it's cmake version 2.8.10.2.

**Comment by deanberris** [comment]
Interesting. This uses the gcc compiler by default, which may explain why you're having some issues. Please try with clang (-DCMAKE_CXX_COMPILER=clang) and see if that fixes it? It might require that you build Boost with clang as well, but it would be worth the try.

**Comment by FlexTheCat** [comment]
Dean, thanks for pointing out the compiler settings.
The solution is in your change logs for 0.11.0:
- Make OS X Clang builds use C++11 and libc++

We use clang with the old stl (libstdc++).

Then the solution is to define
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ 
for netlib creation.

This leads to compatible symbols:
boost::network::uri::detail::parse(__gnu_cxx::__normal_iterator, ....)
compared to
boost::network::uri::detail::parse(std::__1::__wrap_iter, ....)

Regards,
felix
