### ISSUE TITLE
too many deprecated

### ISSUE THREAD

**Issue by qhsong** [cpp-netlib/cpp-netlib#542]
I'm in mac os and got too many deprecated like this:
```
usr/local/lib/cmake/cppnetlib/../../../include/boost/asio/ssl/detail/impl/engine.ipp:316:12: warning:
      'SSL_write' is deprecated: first deprecated in OS X 10.7
```
how to turn off SSL in mac os?

**Comment by deanberris** [comment]
I have no idea, but you can use a more recent OpenSSL instead that you install/build yourself.
