### ISSUE TITLE
Disable optimization, call http::client::post in a loop using the same client object causes a crash on Mac OS LLVM

### ISSUE THREAD

**Issue by anirban001** [cpp-netlib/cpp-netlib#543]
Repro Steps:
1. Mac OS X Yosemite
2. Clang compiler (Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
3. Boost 1.58
4. cpp-netlib 0.11.1
5. Ran a simple python based http server on localhost on 8080.
5. Using post in a loop 

  using namespace boost::network;

  http::client::options options;
  options.follow_redirects(false)
         .cache_resolved(false)
         .timeout(5);
  std::string host_url = "http://127.0.0.1:8080/";
  http::client client(options);
  for (int i = 0; i < 2; ++i) {
    http::client::request request("http://127.0.0.1:8080");
    request << header("connection", "keep-alive");
    request << header("Content-Type", "text/html");
    request << header("Content-Length", "2");
    request << body("ab");
    http::client::response response = client.post(request);
    std::string result = body(response);
    std::cout << result << std::endl;
  }

This creates a crash if you remove the -O3 optimization parameter from /usr/bin/g++. See build script below.

_run_g++() {
  /usr/bin/g++ \
    -DBOOST_NETWORK_ENABLE_HTTPS \
    -Wall \
    -ftemplate-depth=256 -std=c++11 -stdlib=libc++ -DNDEBUG \
    -isystem ${BOOST_DIR}/include \
    -isystem ${CPP_NETLIB_SRC} \
    $*
}

_run_g++ \
  -c ${CPP_NETLIB_SRC}/libs/network/src/client.cpp \
  -o ${OUTPUT_DIR}/client.cpp.o

_run_g++ \
  -c ${CPP_NETLIB_SRC}/libs/network/src/uri/uri.cpp \
  -o ${OUTPUT_DIR}/uri.cpp.o

_run_g++ \
  -c ${CPP_NETLIB_SRC}/libs/network/src/uri/schemes.cpp \
  -o ${OUTPUT_DIR}/schemes.cpp.o

_run_g++ \
  -c ./example.cpp \
  -o ${OUTPUT_DIR}/example.cpp.o

_run_g++ \
  ${OUTPUT_DIR}/example.cpp.o \
  ${OUTPUT_DIR}/uri.cpp.o \
  ${OUTPUT_DIR}/schemes.cpp.o \
  ${OUTPUT_DIR}/client.cpp.o \
  ${BOOST_DIR}/lib/libboost_program_options.a \
  ${BOOST_DIR}/lib/libboost_thread.a \
  ${BOOST_DIR}/lib/libboost_date_time.a \
  ${BOOST_DIR}/lib/libboost_regex.a \
  ${BOOST_DIR}/lib/libboost_system.a \
  ${BOOST_DIR}/lib/libboost_filesystem.a \
  ${BOOST_DIR}/lib/libboost_chrono.a \
  /usr/lib/libssl.dylib \
  /usr/lib/libcrypto.dylib \
  -o ${OUTPUT_DIR}/http_client_bin

${OUTPUT_DIR}/http_client_bin

**Comment by deanberris** [comment]
This has been fixed in 0.11.2 -- can you please confirm by using 0.11.2 instead @anirban001?

**Comment by anirban001** [comment]
Confirming this was fixed on 0.11.2. Thanks.
