### ISSUE TITLE
How to run multiple sync_server in an app?

### ISSUE THREAD

**Issue by xinsuiyuer** [cpp-netlib/cpp-netlib#573]
This's my requirements:
1. Start up sync_server A listen on port 7740.
2. Start up sync_server B listen on port 7741.

After receiving SIGINT, I want to stop A and B gracefully.

Thanks.

**Comment by deanberris** [comment]
You can run two threads, each of which will be running the server:

```c++
auto server1 = std::make_shared<myserver>(...);
auto server2 = std::make_shared<myserver>(...);
auto s1 = std::async([server1] { server1->run(); });
auto s2 = std::async([server2] { server2->run(); });
// install a signal handler
install_handler([server1, server2] { server1->stop(); server2->stop(); });
s1.join();
s2.join();
```

Does that help?

**Comment by xinsuiyuer** [comment]
Thanks @deanberris ,  your demo works fine.
I run these server in new thread in my project, but after calling stop(), server handler  log 'bad file descriptor', it seems that I  use in wrong way.
Thanks again!
