### ISSUE TITLE
Compile error on centos 6 

### ISSUE THREAD

**Issue by akashtalole** [cpp-netlib/cpp-netlib#577]
/usr/local/lib/libboost_thread.a(thread.o):thread.cpp:(.text+0x30c): more undefined references to `clock_gettime' follow
collect2: ld returned 1 exit status
make[2]: *** [tests/cpp-netlib-utils_thread_pool] Error 1
make[2]: Leaving directory `/root/cpp-netlib-0.9.4/build'
make[1]: *** [libs/network/test/CMakeFiles/cpp-netlib-utils_thread_pool.dir/all] Error 2
make[1]: Leaving directory `/root/cpp-netlib-0.9.4/build'
make: *** [all] Error 2

**Comment by deanberris** [comment]
You're using a very old version of cpp-netlib. Please use the latest release (0.11.2) from http://cpp-netlib.org/.

**Comment by akashtalole** [comment]
Solved using latest version.
