### ISSUE TITLE
follow_redirects set true doesn't work  correct, how should i do?

### ISSUE THREAD

**Issue by swpuzhang** [cpp-netlib/cpp-netlib#588]
when I use version 0.11.2 and test follow_redirects:

```
#include <boost/network/protocol/http/client.hpp>
#include <boost/network/uri.hpp>
#include <string>
#include <fstream>
#include <iostream>

namespace http = boost::network::http;
namespace uri = boost::network::uri;

namespace {
    std::string get_filename(const uri::uri &url) {
        std::string path = uri::path(url);
        std::size_t index = path.find_last_of('/');
        std::string filename = path.substr(index + 1);
        return filename.empty() ? "index.html" : filename;
    }
}  // namespace

int main(int argc, char *argv[]) {

    http::client::options options;
    options.follow_redirects(true);
    http::client client(options);
    try {
        http::client::request request("http://www.agoda.com/zh-cn/partners/xml2012_landing.aspx?cid=1463261&currency=USD&asq=HYIrr9YPF%2bxSQOAH8tE9UluM%2bplH0AoF4zZE%2feX6ovI1cvbmIqR3%2fojw5S%2fW71nwqBSvmg5GxcKhjC1IF%2b7jKB%2f4cMfjdQCUkrPv%2fMdNieVnSxROs%2fHFDYx1Zn9%2f21XwfKYegMhijChvTHXVwBWa5ctkFYiNqfy0bvO0bvp1YKk%3d&tag=1f8e8af2086447e491ea69277d0290da3741,BLT_HH_HOTEL");

        http::client::response response = client.head(request);
        std::string filename = get_filename(request.uri());
        std::cout << "Saving to: " << filename << std::endl;
        std::ofstream ofs(filename.c_str());
        http::client::response::headers_container_type head =  (headers(response));
        for (http::client::response::headers_container_type::iterator it = head.begin(); it != head.end(); ++it)
        {
            ofs << it->first << ":" << it->second << "\n";
        }
        //ofs << str << std::endl;
    }
    catch (std::exception &e) {
        std::cerr << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

the result is:

Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Content-Type
Access-Control-Allow-Methods:GET,POST
Access-Control-Allow-Origin:http://www.agoda.com
Cache-Control:private
Connection:close
Content-Length:624
Content-Type:text/html; charset=utf-8
Date:Fri, 22 Jan 2016 02:37:23 GMT
Location:/zh-cn/pages/agoda/default/WaitPage.aspx?asq=HYIrr9YPF%2bxSQOAH8tE9UluM%2bplH0AoF4zZE%2feX6ovI1cvbmIqR3%2fojw5S%2fW71nwx65ejKA6GUa2M28VAVqUuMKBnnR9IEFCgfkWBX33Ppp9Tya9Sy8IGiScXvgqDN27lv%2bLNuV97ywqF5fCQY1po8EXWSMoverueUpQvcMsyBeXDQJMHUEVfEO8OHKYffjrgFT7Zz1rPrNikmtO9qimS8BVH6I7Z94t5akckWhmuyJ2jwxLfV4Aa6w%2btv8rVQia2yDtb1RIQ9OXWuzbL6OLf204lg9IbyJnaFIB7gD%2fntiS1kbuf2sXzJig%2bj5oxItjqiOGbOnQlg0k9eGdqrQdFw%3d%3d&cid=1463261&tag=1f8e8af2086447e491ea69277d0290da3741,BLT_HH_HOTEL&tick=635890522436
Server:Microsoft-IIS/8.5
Set-Cookie:agoda.user.03=UserId=acbad603-8da7-4689-9fc2-1888bb5eec6e; domain=.agoda.com; expires=Sun, 22-Jan-2017 02:37:23 GMT; path=/
Set-Cookie:agoda.deviceinfo.01=DeviceHash=Tm8gVUE=&DeviceInfo=eyJEZXZpY2VQbGF0Zm9ybXMiOjEsIlVzZXJBZ2VudCI6Ik5vIFVBIiwiSXNEZXNrdG9wIjp0cnVlLCJJc01vYmlsZSI6ZmFsc2UsIklzUGhvbmUiOmZhbHNlLCJJc1RhYmxldCI6ZmFsc2UsIklzU3BpZGVyIjpmYWxzZSwiV2lkdGgiOjAsIkhlaWdodCI6MCwiSXNUb3VjaFNjcmVlbiI6ZmFsc2UsIlByZWZlcmVkVmlldyI6bnVsbCwiRGV2aWNlRGV0YWlscyI6eyJGYW1pbHkiOm51bGwsIk1vZGVsIjpudWxsLCJEZXZpY2VJRCI6MCwiS2V5IjpudWxsfSwiT3NEZXRhaWxzIjp7IkZhbWlseSI6Ik90aGVyIiwiTWFqb3IiOiIiLCJNaW5vciI6IiIsIlBhdGNoIjoiIiwiUGF0Y2hNaW5vciI6IiJ9LCJCcm93c2VyRGV0YWlscyI6eyJGYW1pbHkiOiJPdGhlciIsIk1ham9yIjoiIiwiTWlub3IiOiIiLCJQYXRjaCI6IiJ9LCJEZXRlY3Rpb25NZXRob2QiOjF9&DetectionMethod=1&V=3&P=1; domain=agoda.com; expires=Sun, 22-Jan-2017 02:37:23 GMT; path=/

so I have got a 301 page, but it doesn't redirect to the next page, but i use web browser can work correct, how should do to get the last page that is redirected to

**Comment by deanberris** [comment]
Unfortunately this isn't supported by the asynchronous client because it's too fragile to get right. You will have to handle the 301 cases yourself, by looking at the Location header and then following it.
