### ISSUE TITLE
0.11.2 did not get a version bump in CMakeLists.txt

### ISSUE THREAD

**Issue by eco** [cpp-netlib/cpp-netlib#593]
I didn't bother to compare against the git tags for 0.11.2 but some clues:

- The version number in the CMakeLists.txt is 0.11.1.
- The versions of `post` that take a streaming callback appear to be missing (not sure if this was added in 0.11.2 but the documentation lists them).
- The fix for issue #482 is not included.

I didn't check to see if #482's fix was merged to the 0.11 branch but the fix is mentioned in the changelog so it should be included.

All three downloads (.zip, .tar.gz, and .tar.bz2) had the wrong version number in CMakeLists.txt though I didn't check to see if all three were missing the fix for #482 (the .zip definitely was).

**Comment by eco** [comment]
Just confirmed that the tag cpp-netlib-0.11.2-final also does not have the fix for #482.

**Comment by eco** [comment]
Nor does the 0.11-devel branch.

**Comment by eco** [comment]
Oh, I see what happened. The fix is still there, it was just redone a bit by 57f1e97.

Also, I do see the streaming callback version of `post` now (it's kind of confusing that the naming is all different from the documentation but no matter).

The version number is still wrong. I'll change the issue title to reflect just that part.

**Comment by deanberris** [comment]
Yes, this was a mistake on my end, I've updated the package script to make this happen more automatically. Hopefully this doesn't happen again in the future.
