### ISSUE TITLE
is CMake/building necessary?

### ISSUE THREAD

**Issue by mattrmunson** [cpp-netlib/cpp-netlib#594]
The getting started page says "The cpp-netlib uses CMake to generate platform-specific build files. If you intend to run the test suite, you can follow the instructions below. Otherwise, **you don’t need CMake to use cpp-netlib in your project**. The cpp-netlib requires CMake version 2.8 or higher."

So this sounds like I don't need to build anything with CMake unless I want to do the tests. However, I'm having trouble compiling this [http client](http://cpp-netlib.org/0.11.2/examples/http/http_client.html), and it seems like everyone is linking against libraries: [1](http://stackoverflow.com/questions/15055298/how-to-link-against-cpp-netlib), [2](https://groups.google.com/forum/#!topic/cpp-netlib/lcaOrRyyFTg) (`-lcppnetlib-uri`, `-llibcppnetlib-client-connections`).

here is my compile instructions, for mingw48:
```
g++ -I netlib/ -I boost_1_60_0/ client.cpp ^
-L boost_1_60_0/stage/lib -lboost_system-mgw48-mt-1_60 ^
-lboost_thread-mgw48-mt-1_60 -lws2_32
```

**Comment by deanberris** [comment]
The CMake build allows users of the library that use CMake as well to depend on the library in their projects. It also makes changing the dependencies more straight-forward for the library code as well.

I suspect if you don't want to use CMake, there's a way to build the libraries by hand too.

That said I don't think we're ever likely to remove CMake for building the libraries and the tests.

**Comment by deanberris** [comment]
Also, I think this is a bug in the documentation. So I'm not going to close this for now.

**Comment by mattrmunson** [comment]
Cool. I don't have a problem with using CMake. I just got confused, because I thought that, if it's not necessary, I won't bother. And it seems like the documentation is saying that its not necessary.

**Comment by glynos** [comment]
I updated this part of the documentation for the 0.13 release. Sorry it took so long.
