### ISSUE TITLE
cpp-netlib-http-client_get_timeout_test ***Failed

### ISSUE THREAD

**Issue by mattrmunson** [cpp-netlib/cpp-netlib#596]
I ran make test and all the tests passed until test 15, which makes the program hang (I was prompted by OS to click close) then it gets stuck waiting on test 17.

Im on win 8.1, mingw48, boost_1_60_0, cpp-netlib-0.11.2-final, and openSSL 0.9.8 (C:\Program Files (x86)\Intel\iCLS Client)

 cmake -G "MinGW Makefiles" ^
       -DCMAKE_BUILD_TYPE=Debug ^
       -DCMAKE_C_COMPILER=gcc ^
       -DCMAKE_CXX_COMPILER=g++ ^
       -DBOOST_ROOT=C:\Users\matt\Desktop\boost_1_60_0 ^
       -DBOOST_LIBRARYDIR=C:\Users\matt\Desktop\boost_1_60_0\stage\lib ^
       ../netlib

Start  1: cpp-netlib-message_test
 1/19 Test  #1: cpp-netlib-message_test .............................   Passed
  0.02 sec
      Start  2: cpp-netlib-message_transform_test
 2/19 Test  #2: cpp-netlib-message_transform_test ...................   Passed
  0.01 sec
      Start  3: cpp-netlib-utils_thread_pool
 3/19 Test  #3: cpp-netlib-utils_thread_pool ........................   Passed
  0.01 sec
      Start  4: cpp-netlib-uri_test
 4/19 Test  #4: cpp-netlib-uri_test .................................   Passed
  0.02 sec
      Start  5: cpp-netlib-uri_builder_test
 5/19 Test  #5: cpp-netlib-uri_builder_test .........................   Passed
  0.02 sec
      Start  6: cpp-netlib-uri_builder_stream_test
 6/19 Test  #6: cpp-netlib-uri_builder_stream_test ..................   Passed
  0.02 sec
      Start  7: cpp-netlib-uri_encoding_test
 7/19 Test  #7: cpp-netlib-uri_encoding_test ........................   Passed
  0.01 sec
      Start  8: cpp-netlib-relative_uri_test
 8/19 Test  #8: cpp-netlib-relative_uri_test ........................   Passed
  0.01 sec
      Start  9: cpp-netlib-http-response_incremental_parser_test
 9/19 Test  #9: cpp-netlib-http-response_incremental_parser_test ....   Passed
  0.01 sec
      Start 10: cpp-netlib-http-request_incremental_parser_test
10/19 Test #10: cpp-netlib-http-request_incremental_parser_test .....   Passed
  0.01 sec
      Start 11: cpp-netlib-http-request_linearize_test
11/19 Test #11: cpp-netlib-http-request_linearize_test ..............   Passed
  0.02 sec
      Start 12: cpp-netlib-http-client_constructor_test
12/19 Test #12: cpp-netlib-http-client_constructor_test .............   Passed
  0.02 sec
      Start 13: cpp-netlib-http-client_get_test
13/19 Test #13: cpp-netlib-http-client_get_test .....................   Passed
 17.58 sec
      Start 14: cpp-netlib-http-client_get_different_port_test
14/19 Test #14: cpp-netlib-http-client_get_different_port_test ......   Passed
  8.19 sec
      Start 15: cpp-netlib-http-client_get_timeout_test
15/19 Test #15: cpp-netlib-http-client_get_timeout_test .............***Failed
 87.57 sec
      Start 16: cpp-netlib-http-client_get_streaming_test
16/19 Test #16: cpp-netlib-http-client_get_streaming_test ...........   Passed
  1.43 sec
      Start 17: cpp-netlib-http-server_constructor_test

**Comment by deanberris** [comment]
Can you attach the logs? It should be in `Testing/Temporary/LastTest.log` from the build directory.

**Comment by glynos** [comment]
FYI, I disabled this test completely on the master branch. It is a poor test.

**Comment by mattrmunson** [comment]
[LastTest.log.tmp.txt](https://github.com/cpp-netlib/cpp-netlib/files/121424/LastTest.log.tmp.txt)

**Comment by deanberris** [comment]
Right, as @glynos points out this is caused by a flaky testing approach. These failures could be ignored just fine. If you really want to just build the libraries, setting `CPP-NETLIB_BUILD_TESTS` to `OFF` should allow you to move forward without needing to build/run the tests.
