### ISSUE TITLE
Not-catched exception in boost::network::http::async_connection::start

### ISSUE THREAD

**Issue by ikrukov** [cpp-netlib/cpp-netlib#611]
exceptions is thrown in this line:

 ip_stream << socket_.remote_endpoint().address().to_v4().to_string() << ': '<<socket_.remote_endpoint().port();

Method to_v4 throws "bad_cast" when address is considered as v6 address.

For me its looks like bug, because it may be not obvious if listening address will be considered as v6 address. I faced with this problem when deployed application to Ubuntu 14.04 server, and run it on "localhost" address. In server address "localhost" is linked both to 127.0.0.1 ( v4 address ) and to ::1/128 (v6 address). Because of this application crashed on server, but runs perfectly on machines without ip v6 installed.

**Comment by deanberris** [comment]
What version is this in? Can you try using the master version to see if this is still a problem?

**Comment by ikrukov** [comment]
HI Dean,

I've tried version which is provided with Ubuntu 14.04. AFAIK it was 0.11.0. As I can see the method async_connection::start wasn't changed since 0.11.0. So this issue should affect master version too.  But I will do additional check when I'll get to my work computer.

P.S.
May be I was not clear enough in my report - there is no problem in this method if in /etc/hosts file localhost address is bound to ipv4 address only. For example in desktop version of Ubuntu 14.04 async server can listen on localhost and accept connections perfectly. But in server version there is additional ipv6 address ::1 for localhost. Because of this localhost is considered as ipv6 address and throws exception in to_v4 method. ( Of course this issue can be fixed easily by using 127.0.0.1 instead of localhost in my case.)

**Comment by deanberris** [comment]
Yes, this is bad. I'll give it a few minutes to see if I can fix it.
