### ISSUE TITLE
HTTP headers as map ?

### ISSUE THREAD

**Issue by avalchev** [cpp-netlib/cpp-netlib#615]
As a user, it's more convenient for me, to have headers as std::map, instead std::vector and iterate over them.

Is there any reason for using std::vector instead of std::map ?

Thanks.

**Comment by deanberris** [comment]
In the HTTP server, we don't want to make too many small allocations with the std::map or a std::multimap so we can parse the data in a straight line. This was a tradeoff between performance and convenience. At one time I thought about turning this into a std::multimap but I decided against it for the overhead involved in jumping around non-contiguous memory.

My suggestion is, once you have the std::vector, you can std::sort it if you want, then do a std::lower_bound and std::upper_bound. Or, you can create your own map from it.

Later on I think it's worth making it possible for users to choose whether they want a multimap or a vector for the headers. That would make it a little more complicated, but maybe worth it for users that value the convenience of the std::multimap over the vector.
