### ISSUE TITLE
Error Compiling cpp-netlib

### ISSUE THREAD

**Issue by Bardo91** [cpp-netlib/cpp-netlib#618]
Hi, 
I'm trying to compile the library but I got this error (among others similar from the same include folder):

        fatal error: asio/ip/tcp.hpp: No such file or directory
                       #include <asio/ip/tcp.hpp>

I check, and I've boost properly installed and is in the default place. Also I check that I've that file, but it is like the include sentence needs a "boost/" before it. But I think that it is a really obvious thing to be an undetected error. What am I doing wrong? I've Boost 1.60, could that be the reason?

**Comment by augustjd** [comment]
Just compiled against boost 1.60, so that's not your problem.

**Comment by luciantodor** [comment]
Hi. I have used stable version of cpp-netlib 0.11.2-final and it was ok to compile. Because I intend to test and use a newer version, I'm curious, what version are you using?
Thanks.

**Comment by augustjd** [comment]
The same. 0.11.2-final.
On Mar 26, 2016 9:42 AM, "Lucian Todor" <notifications@github.com> wrote:
>
> Hi. I have used stable version of cpp-netlib 0.11.2-final and it was ok
to compile. Because I intend to test and use a newer version, I'm curious,
what version are you using?

**Comment by mikhailberis** [comment]
It seems that you are using a 0.12.0-rc* because we've stopped depending on Boost.Asio and instead rely on the standalone Asio release. If you follow the instructions in the README regarding submodules then it should work.

**Comment by Bardo91** [comment]
Hi, I just cloned the git repository and compiled it from there. So I assume is the latest code. Could it be the reason so?

**Comment by deanberris** [comment]
Yes, this is the reason. I don't think we updated the README for building from git yet, so let me fix that soon. In short you're going to need to:

    git submodule init
    git submodule update

Or, if you're cloning from scratch, you might want to recursively deal with the submodules in a single command. Like:

  git clone --recursively https://github.com/cpp-netlib/cpp-netlib

**Comment by Wuodan** [comment]
I had the same error using the release 0.12.0.tar.gz from github.
No problem with the tar.gz from http://downloads.cpp-netlib.org/.
`fatal error: asio/ip/tcp.hpp: No such file or directory
                   #include <asio/ip/tcp.hpp>`


The tar.gz from github also had a different folder name after unpacking than the one from cpp-netlib.org.

Release 0.11.1 was not affected by these 2 phenomenas.
