### ISSUE TITLE
0.12.0-final release tag?

### ISSUE THREAD

**Issue by ilovezfs** [cpp-netlib/cpp-netlib#620]
Would it be possible to get 0.12.0-final tagged? cpp-netlib-0.12.0-rc1 is a dependency of osquery 1.7.2, but usually Homebrew requires actual release tags, not release candidate tags, to be used for the stable specs. Are there any show stoppers preventing a 0.12.0-final release tag? Thanks!

https://github.com/Homebrew/homebrew/pull/50362#issuecomment-200870340
https://github.com/facebook/osquery/pull/1918
https://github.com/facebook/osquery/issues/1920

**Comment by deanberris** [comment]
I'm going to tidy up the master branch and create an -rc2 which should also be -final after a quick round of testing/qualification.

**Comment by deanberris** [comment]
Tagged cpp-netlib-0.12.0-rc2, which should turn into cpp-netlib-0.12.0-final unless things break unexpectedly. See https://github.com/cpp-netlib/cpp-netlib/tree/cpp-netlib-0.12.0-rc2

**Comment by ilovezfs** [comment]
@deanberris Thanks: https://github.com/Homebrew/homebrew/pull/50375
