### ISSUE TITLE
Example Server Code in 0.12.0 Documentation uses 'response'; doesn't compile

### ISSUE THREAD

**Issue by MMOSimca** [cpp-netlib/cpp-netlib#624]
http://cpp-netlib.org/0.12.0/index.html

The Hello World HTTP server examples listed in the documentation will not compile because the 'server::response' member is now unused (I guess? First time user) in favor of 'server::connection_ptr' (at least that is what the included hello_world_server.cpp has replaced it with).

This ended up being a significant issue for me because I assumed it was simply my fault for trying to be fancy and do it in Windows (VS 2015), so I then spent several hours trying to get it working in Linux as well, which I'm not super great at (so I again assumed it was my fault).

I probably should have tried looking elsewhere for an example or looking at the documentation for 'response' and seeing it changed or tried an older version, etc; just pointing out that there is an issue.

**Comment by deanberris** [comment]
Oh, yes, that's broken. 😦

Do you have time to fix this and send a pull request to the 0.12-release branch?

**Comment by glynos** [comment]
Fixed in 0.12, and the documentation is updated in 0.13 :)
