### ISSUE TITLE
asio needed for building with cpp-netlib (0.12.0)

### ISSUE THREAD

**Issue by susnux** [cpp-netlib/cpp-netlib#629]
As of 0.12.0 cpp-netlib uses asio instead of boost/asio, so if you do not have asio-devel (or something like this) installed building with cpp-netlib will fail.
This took me only maybe 2 minutes, but a hint in the documentation that asio has to be installed would be great.

**Comment by glynos** [comment]
I don't understand this issue: asio is a submodule of the cpp-netlib repo, and the build system should be able to find it.

In principle, the only external dependency that cpp-netlib 0.12 needs are boost, OpenSSL and pthread.

**Comment by susnux** [comment]
Yes but if you install it and then try to compile a program using cpp-netlib, asio has to be installed also.

**Comment by glynos** [comment]
OK, so it's a configuration/packaging issue. Thanks.

**Comment by susnux** [comment]
Yes either it got installed by netlib or a comment in the documentation would be great.
Nothing big here ;-)

**Comment by MMOSimca** [comment]
Worked fine for me in VS2015 on Windows, but I did have to specifically point the project to the asio files.

**Comment by glynos** [comment]
So we won't use standalone asio going forward. The upcoming 0.13 release will revert to using Boost.Asio, and the master branch now uses Boost.Asio.
