### ISSUE TITLE
Lacking support for raw body data in POST & GET requests?

### ISSUE THREAD

**Issue by DashW** [cpp-netlib/cpp-netlib#632]
I've hit a problem recently where I've wanted to POST the contents of an image file, but since the API only supports strings in the message body, the message is being terminated at the first null character despite specifying "Content-Length" in the headers.

I've encountered similar problems when trying to GET image data too - the iterator_range return type means that the problem can be fixed, but perhaps isn't as clear as something like a boost::buffer.

Any plans to address this?

**Comment by luciantodor** [comment]
Hi Dash,

I have used cpp-netlib 0.11.2 in the recent past and upload/download binary files (also with null characters).
std::string can hold null characters. See an example for the constructor here: http://www.cplusplus.com/reference/string/string/string/.

Try to use the asynchronous methods, those with handlers.

**Comment by luciantodor** [comment]
Note: the "Content-Length" header has to be set also.

**Comment by DashW** [comment]
Aha. I was mistaken.
My problem was not with null characters, my problem was with the buffer size for an asynchronous request response - at present this is limited to 1024 bytes:

In: https://github.com/cpp-netlib/cpp-netlib/blob/master/boost/network/protocol/http/client/connection/async_protocol_handler.hpp, line 338:
```
// TODO(dberris): make 1024 go away and become a configurable value.
typedef std::array<typename char_<Tag>::type, 1024> buffer_type;
```

Not to mention that the buffer size for a POST request is limited to 1MB.

I'm not sure what the best solution might be in this case. Recompile CPP-NETLIB with (much) higher buffer sizes, or concatenate the buffers together until... what? Until I get a buffer smaller than 1024 bytes? Until my callback stops being invoked?

**Comment by DashW** [comment]
I'm now concatenating buffers together until I receive one that's smaller than 1024 bytes, but I'm not sure if this is the most correct approach.

**Comment by luciantodor** [comment]
When I used this library I had no issues about the buffer size. My approach and my recommendation is to use an asynchronous approach. I have found a good example where you can look here: https://github.com/cpp-netlib/cpp-netlib/issues/457

In the body_handler() you have to manage the receive body range yourself. Either passed it to a file stream or append it to a string.

I hope this will help you.

**Comment by DashW** [comment]
Aha! Notice how the body_handler() in your example appends the content to a string until it receives a boost::asio::error::eof! So I'm guessing that's the correct way to know when the last buffer is received. That's all I needed to know. Sorry for the confusion, and thanks for your help.

**Comment by glynos** [comment]
@DashW What's missing here? Just documentation, or can the API be improved?

**Comment by DashW** [comment]
I think a little of both. Firstly documentation, or examples, would be useful to know the "correct" way of using the asynchronous API, **BUT** I think a better solution would be to change the API to concatenate the file contents *before* providing it to the callback. In my experience, when I make an asynchronous call, I expect the callback I provide to be called exactly once.

**Comment by deanberris** [comment]
Thanks @DashW -- there may be a middle-ground here, because there are different trade-offs to be made when implementing a request handler that might be getting a ton of data (say a file upload) which might take more memory if we pre-concatenate the data. For the simple cases where you have bodies that don't take a lot of input data, it does make some sense.

I suspect some helper functions for the feature you're suggesting might work to make it simpler.

Let me think about this a little more, but I do appreciate your feedback!
