### ISSUE TITLE
Including Boost.Asio before cpp-netlib causes compile error

### ISSUE THREAD

**Issue by amerry** [cpp-netlib/cpp-netlib#634]
If I do something like

    #include <boost/asio/ip/address.hpp>
    #include <boost/network.hpp>

then compilation fails because the references to things like `asio::io_service` in cpp-netlib resolve to the `boost::asio` namespace (since the code is in the `boost::network` namespace).

While I can just reorder the headers, this is still not an ideal situation. Presumably, this could be solved by using absolute references, like `::asio::io_service`.

**Comment by deanberris** [comment]
Yes, this is bad. I see @glynos has taken this on.

Do you mind fixing this in the 0.12-release branch too so that we can release a 0.12.1 soon to remedy this?

**Comment by glynos** [comment]
@amerry Could you check that the latest changes work for you?

**Comment by amerry** [comment]
Yep, 0.12-release now works.

**Comment by avalchev** [comment]
Could you please merge it into master.

**Comment by glynos** [comment]
@avalchev These changes were already committed on master in a separate PR:

https://github.com/cpp-netlib/cpp-netlib/commit/f2095b6850fbccdfc7b814866ae12c09b6f864bd
