### ISSUE TITLE
async_connection: read function calls callback with too few parameters

### ISSUE THREAD

**Issue by susnux** [cpp-netlib/cpp-netlib#635]
Having a look at:
[async_connection.hpp line 395](https://github.com/cpp-netlib/cpp-netlib/blob/de9194d7e2525baca2711f40aa1d7b8ed96667d1/boost/network/protocol/http/server/async_connection.hpp#L395)

The read function from async_connection calls the read_callback_function with 2 instead of 4 needed parameters, this leads into this compiling issue (when using the read function):

    async_connection.hpp | 395 |
    error: no match for call to ‘(const read_callback_function {aka const std::function<void(boost::iterator_range<const char*>, std::error_code, long unsigned int, std::shared_ptr<boost::network::http::async_connection<boost::network::http::tags::http_server, {anonymous}::serverhandle> >)>}) (std::error_code&, size_t&)’|

First reported here: [cpp-netlib google groups](https://groups.google.com/d/msg/cpp-netlib/fgiy6c3kSc0/MiB9502VAAAJ)

**Comment by susnux** [comment]
I am not sure, but I think something like this should work (?)

```diff
diff --git a/boost/network/protocol/http/server/async_connection.hpp b/boost/network/protocol/http/server/async_connection.hpp
index e5c361a..32fb7f9 100644
--- a/boost/network/protocol/http/server/async_connection.hpp
+++ b/boost/network/protocol/http/server/async_connection.hpp
@@ -388,11 +388,10 @@ struct async_connection
       return;
     }
 
-    auto self = this->shared_from_this();
     socket().async_read_some(asio::buffer(read_buffer_),
-                             strand.wrap([this, self, callback](
+                             strand.wrap([this, callback](
                                  std::error_code ec, size_t bytes_transferred) {
-                               callback(ec, bytes_transferred);
+                               this->wrap_read_handler(callback, ec, bytes_transferred);
                              }));
   }

```

**Comment by susnux** [comment]
Question: Are the fixes also going to be merged back into master?

**Comment by deanberris** [comment]
@susnux It should be, I'll cherry-pick it in soon.

**Comment by MMOSimca** [comment]
To say this is a pretty huge bug is kind of an understatement (all reading of request bodies for servers broken) - maybe there should be a 0.12.1 release for this fix?

**Comment by susnux** [comment]
I think @deanberris (?) is working on a bugfix release 0.12.1
