### ISSUE TITLE
multiple definitions of `swap` from thread_pool.hpp

### ISSUE THREAD

**Issue by Plaristote** [cpp-netlib/cpp-netlib#643]
Greetings !

In `boost/network/utils/thread_pool.hpp`, line 101, there's global swap function that gets declared. The problem is, it's not inline, and the compiler complains about multiple definition for each target that includes thread_pool.hpp.

Seeing the history, this function used to be a template, 20 days ago or so. As a template, this issue wouldn't happen: but as a global function, we have to either declare it as `inline`, or define it away from the headers.
As far as I know, there's no other way to go around that.

**Comment by deanberris** [comment]
Oops. You're right. I'm fine with making it `inline`. I'll get to this soon enough.

**Comment by deanberris** [comment]
@Plaristote -- this is in the master branch, yes?
