### ISSUE TITLE
cpp-netlib can't build in visual studio 2013

### ISSUE THREAD

**Issue by qmqsyz** [cpp-netlib/cpp-netlib#644]
My system is Windows 7, I download the cpp-netlib 0.12.0-final, and my boost is 1.60, I use cmake to generate visual studio 2013 project, but there are some error, i try to repair some error.

cpp-netlib-0.12.0-final\boost\network\message.hpp
  basic_message(const basic_message&) = default;
  basic_message(basic_message&&) = default;
  basic_message& operator=(basic_message const&) = default;
  basic_message& operator=(basic_message&&) = default;
I dedele "= default"

cpp-netlib-0.12.0-final\boost\network\protocol\http\client\async_impl.hpp  
  ~async_client() throw() = default;
changed:
  ~async_client() = default;

cpp-netlib-0.12.0-final\boost\network\protocol\http\client\connection\async_protocol_handler.hpp
    debug_escaper(debug_escaper const&) = default;
    debug_escaper(debug_escaper&&) noexcept = default;
changed:
    debug_escaper(debug_escaper const&);
    debug_escaper(debug_escaper&&);

But there are some othre question I can't resolve.
cpp-netlib-0.12.0-final\boost\network\protocol\http\client\connection
351:  callback(make_iterator_range(begin, end), ec);
420:  callback(make_iterator_range(begin, end), ec);

visual studio show can't convert type:
boost::iterator_range<std::_Array_const_iterator<_Ty,1024>>
can not convert
const boost::iterator_range<const boost::network::uri::uri::value_type *> &:

**Comment by deanberris** [comment]
Does MSVC 2013 support C++11 features we're using here? Could it be that you need to just enable C++11 mode for MSVC 2013, and don't have to modify the 0.12.0-final release sources?

**Comment by glynos** [comment]
I think this issue was fixed (0.13-release), but we have not tested for MSVC 2013, and we are not going to. Therefore, I will close this issue. MSVC 2015 will be supported for the 0.13 release and beyond.
