### ISSUE TITLE
VS2015 doesn't build all libraries

### ISSUE THREAD

**Issue by 4Nick** [cpp-netlib/cpp-netlib#649]
Hello,
I've been trying to compile cpp-netlib using Visual Studio 2015. I read the documentation carefully on how to build it, but I'm still getting a lot of errors.

[VS Output.txt](https://github.com/cpp-netlib/cpp-netlib/files/245622/VS.Output.txt)
Not even all projects were built.
As said in the documentation, I should find all built libraries in the libs/network/src folder, which I did. However, I only see these files (Debug folder):

`cppnetlib-client-connections.lib
cppnetlib-client-connections.pdb
cppnetlib-uri.lib
cppnetlib-uri.pdb`

However, the documentation says I should see these files:
`cppnetlib-client-connections.lib
cppnetlib-server-parsers.lib
cppnetlib-uri.lib`

I'm missing cppnetlib-server-parsers.lib, but the rest was built properly. I don't know where I screwed up, it's the first time I'm trying to build a library and I feel kind of lost here. Does anyone know what I could have done wrong? 

Thank you!

**Comment by samuelts** [comment]
The same as you.
When build project `cppnetlib-server-parsers`, vs2015 tips `error C2872: “true_type”: ambiguous symbol` #648

**Comment by glynos** [comment]
@4Nick Do the changes on the 0.13-release branch fix this problem?

**Comment by glynos** [comment]
cpp-netlib 0.13-release branch builds and tests succeed on MSVC 2015, so I will close this.
