### ISSUE TITLE
cpp-netlib 0.12.0-final can't build success with vs2015 and boost 1.6.0

### ISSUE THREAD

**Issue by qmqsyz** [cpp-netlib/cpp-netlib#651]
async_normal.hpp

```
412:            if (callback) {
413:              // Here we have a body_handler callback. Let's invoke the
414:              // callback from here and make sure we're getting more data right
415:              // after.
416:              typename protocol_base::buffer_type::const_iterator begin =
417:                  this->part.begin();
418:              typename protocol_base::buffer_type::const_iterator end = begin;
419:              std::advance(end, bytes_transferred);
420:              callback(make_iterator_range(begin, end), ec);
```

async_normal.hpp(420): note: Reason: cannot convert from 'boost::iterator_rangestd::_Array_const_iterator<_Ty,1024>' to 'const boost::iterator_range<const boost::network::uri::uri::value_type *>'
with
[
  _Ty=boost::network::char_boost::network::http::tags::http_async_8bit_udp_resolve,void::type
]

it can't build success, then I try to use cpp-netlib developed and cpp-netlib 0.11.2, it's same error. How to resolve it? Thanks!

**Comment by deanberris** [comment]
I don't have access to MSVC 2015, but this looks like the iterator types for std::array and what we're looking for in the callback are incompatible. Can you try changing the type of the iterator in the function callback type to see if that fixes it? And if it does, can you send a pull request to the 0.12-release branch so we can release a 0.12.1 soon?

**Comment by glynos** [comment]
@qmqsyz can you let me know if the 0.13-release branch works or not?

**Comment by enricodetoma** [comment]
I didn't have this problem when building with the 0.13 branch with MSVC2015. **But** I didn't build examples and tests, so today I'll try to build them too and let you know.

**Comment by enricodetoma** [comment]
With pull request #699 everything in the 0.13 branch can be built with MSVC2015, so I think this issue can be closed.
