### ISSUE TITLE
Asio requires static boost?

### ISSUE THREAD

**Issue by burannah** [cpp-netlib/cpp-netlib#655]
Hi, 

I am new to cpp-netlib, so probably this has been already discussed somewhere, but I wasn't able to find it. 
I am trying to compile cpp-netlib on Win7 with VS2015(Update 2). And I think that Asio requires some boost static libraries to be linked with (date_time and regex for example). Is it normal? I'm asking because I saw this in CMakeLists.txt:
```
# Always use Boost's shared libraries.
set(Boost_USE_STATIC_LIBS OFF)
```
And there is no additional library path parameters to make boost static libs available for linker.

Kind Regards

**Comment by mikhailberis** [comment]
> On 18 May 2016, at 00:56, Andrey Khokhlov <notifications@github.com> wrote:
> 
> Hi,
> 
> I am new to cpp-netlib, so probably this has been already discussed somewhere, but I wasn't able to find it. 
> I am trying to compile cpp-netlib on Win7 with VS2015(Update 2). And I think that Asio requires some boost static libraries to be linked with (date_time and regex for example). Is it normal? I'm asking because I saw this in CMakeLists.txt:
> 
> # Always use Boost's shared libraries.
> set(Boost_USE_STATIC_LIBS OFF)
> And there is no additional library path parameters to make boost static libs available for linker.
> 
> 

Hi Andrey,

What version of the library using?

Can you paste the errors that you're getting?

**Comment by burannah** [comment]
Hi Dean,

I am using cpp-netlib master at `9c332f111d694713fb2c340a952b1dfbe14d0f3f` with boost 1.59

While compiling for example `cpp-netlib-http-server_async_run_stop_concurrency` 
I see this error.
```
10>------ Build started: Project: cpp-netlib-http-server_async_run_stop_concurrency, Configuration: Debug Win32 ------
...
10>LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc140-mt-gd-1_59.lib'
```
I think this library dependency comes from Asio (dumpbin util says that also it wants to have regexp library)

If I try to compile cpp-netlib with really standalone Asio (-DASIO_STANDALONE instead of -DASIO_HEADERS_ONLY) - this error (and dependency) is gone, but cpp-netlib won't compile due to deadline_timer is not available in Asio standalone.

**Comment by deanberris** [comment]
So, the latest in master is in a state of flux -- @glynos and I are actively working on that branch. We don't have access to MSVC or Windows machines, but if you have time @burannah we'd appreciate pull requests to make them build.

**Comment by burannah** [comment]
Well, I can try.
But I'm  still not sure how it should work? With -DASIO_HEADERS_ONLY linking static date_time and regex (and maybe a couple more) or with -DASIO_STANDALONE and removing all timer's?

**Comment by burannah** [comment]
I've submitted pool request #659
