### ISSUE TITLE
cpp-netlib-0.12.0-final requires boost_1_58_0 or latter versions

### ISSUE THREAD

**Issue by shapowang** [cpp-netlib/cpp-netlib#661]
I download cpp-netlib-0.12.0-final and my boost version is boost_1_57_0
When I compile,error occurs:
`cpp-netlib-0.12.0-final/boost/network/protocol/http/server/impl/parsers.ipp:14:10: fatal error: 'boost/fusion/include/std_tuple.hpp' file not found`

1.Unzip cpp-netlib-0.12.0-final.tar.gz,the CMakeLists.txt says "find_package(Boost 1.57.0 REQUIRED)"

2.
http://cpp-netlib.org/0.12.0/getting_started.html#getting-started
Getting Boost
cpp-netlib depends on Boost. It should work for any version of Boost above 1.50.0.

That's both wrong,boost/fusion/include/std_tuple.hpp exists in boost_1_58_0 and latter versions.

**Comment by glynos** [comment]
This is fixed in the CMakeLists.txt file and the documentation on 0.13-release. Thanks for the report.
