### ISSUE TITLE
Cannot build program that uses cpp-netlib 0.12.0: asio/ip/address.hpp file not found

### ISSUE THREAD

**Issue by HighCommander4** [cpp-netlib/cpp-netlib#666]
I tried upgrading an application that uses cpp-netlib from version 0.11.2 to 0.12.0.

When trying to build the application, I get:

> cpp-netlib/include/boost/network/uri/builder.hpp:9:10: fatal error: 'asio/ip/address.hpp' file not found

I notice the source distribution contains a `deps/asio` folder, but `make install` doesn't seem to install that anywhere.

**Comment by HighCommander4** [comment]
Manually copying `$SRCDIR/deps/asio/asio/include/asio` to `$CMAKE_INSTALL_PREFIX/include/asio` fixes the problem.

**Comment by biot023** [comment]
I got bit by this at the end of a long day yesterday, and your quick fix saved me a lot of frustration this morning -- thankyou so much!

**Comment by glynos** [comment]
We're going to recommend that people don't use 0.12 in the future, that release introduced a number of important issues, including this installation issue. I am sorry that you lost time because of this.

**Comment by biot023** [comment]
I didn't lose loads -- like I said, it was the end of the day, and I found HighCommander4's suggestion this morning, so that was all to the good! :)
So is there a stable version after 0.12 that is currently recommended? I'll switch to that, if there is.

**Comment by glynos** [comment]
Take a look at the 0.13-release branch. It uses Boost.Asio, and not standalone asio, so you won't need to manually copy the sources.

**Comment by ksl67** [comment]
cpp-netlib.org states that 0.12.0-final is the latest stable release. But you are saying that we should be using the 0.13-release branch. It looks like this is being actively worked on. Is it stable?

**Comment by ksl67** [comment]
@deanberris Perhaps you can comment?

**Comment by deanberris** [comment]
The 0.13-release is waiting on @glynos or me getting around to packaging and updating the documentation of the changes. As far as I'm concerned, what's in 0.13-release will be 0.13.0 (except for some documentation updates and re-generating of the HTML and updating the website).

We certainly think it's stable now because we don't expect any more changes.

How important is it to you @ksl67 that a tagged/released version of 0.13.0 be done soon?

**Comment by ksl67** [comment]
> How important is it to you @ksl67 that a tagged/released version of 0.13.0 be done soon?
@deanberris Well, obviously the sooner the better. But if as you say it's pretty much complete, then I can work with that for now.
Thanks.

**Comment by ksl67** [comment]
deanberris commented on Oct 13, 2016
> The 0.13-release is waiting on @glynos or me getting around to packaging and updating the documentation of the changes. As far as I'm concerned, what's in 0.13-release will be 0.13.0 (except for some documentation updates and re-generating of the HTML and updating the website).

Just noted that 0.13 has still not been released. Do you have an update?

**Comment by anonimal** [comment]
@ksl67 I see that these milestone issues are still open https://github.com/cpp-netlib/cpp-netlib/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.13
