### ISSUE TITLE
"certificate verify failed" error when making HTTPS request

### ISSUE THREAD

**Issue by HighCommander4** [cpp-netlib/cpp-netlib#667]
I'm getting a "certificate verify failed" error when making an HTTPS request using the client API.

I'm getting this error only when running the client on a particular machine (a shared hosting machine); on my development machine, it works fine.

I do not control the server, but its SSL certificates are in order (browsers etc. do not complain about it).

Any help in how to diagnose this further is appreciated. I'm using cpp-netlib version 0.12.0.

**Comment by zwass** [comment]
Did you find anything more about this? We may be seeing a similar problem and it would be helpful to hear what you did.

**Comment by HighCommander4** [comment]
Unfortunately not. I switched to using `wget` as a temporary workaround. I would be interested in finding a solution to this problem and being able to resume using cpp-netlib.

**Comment by deanberris** [comment]
The default changed from "do not verify peer" to "always verify peer" in 0.12.0 -- if you want to go back to the behaviour in 0.11.x then you can set the client option to false. That's:

http://cpp-netlib.org/0.12.0/reference/http_client.html#client-options

In particular, it's specifically the "always_verify_peer" option:

http://cpp-netlib.org/0.12.0/reference/http_client.html#_CPPv2N5boost7network4http14client_options18always_verify_peerEb
