### ISSUE TITLE
TLSv1_2 issue

### ISSUE THREAD

**Issue by bsdunx** [cpp-netlib/cpp-netlib#682]
I've noticed support for TLSv1_2 has been added but I'm having issues getting it to work, I've played around with the http::client::options to no avail.

terminate called after throwing an instance of 'std::system_error'
  what():  tlsv1 alert internal error

Anyone able to offer some guidance on this?

**Comment by bsdunx** [comment]
I've determined SNI support is required to resolve this issue.

**Comment by deanberris** [comment]
Is there anything that needs to be done aside from what's already there in the library @bsdunx?

**Comment by bsdunx** [comment]
@deanberris It seems to be a bit awkward to use having to specify it on a per-request basis, but I do have it working.

**Comment by bsdunx** [comment]
The following seems to be working for me on non-SNI hosts and IP addresses
`http::client::response get(std::string uri) {
    http::client::request request(uri);

    http::client::options options;
    options.follow_redirects(true).cache_resolved(true)
        .openssl_sni_hostname(request.host());

    http::client client = http::client(options);
    return client.get(request);
}`

**Comment by deanberris** [comment]
I agree, this seems to be making for a good case to have per-request options (cc'ing @glynos who's working on redesigning the API for the client).

OK to close this now?

**Comment by bsdunx** [comment]
closing
