### ISSUE TITLE
Add the "Connection: close" header to the request, but Stuck at fetching response body

### ISSUE THREAD

**Issue by chenzhaoyu** [cpp-netlib/cpp-netlib#712]
I Add the "Connection: close" header to the request, but my server(opentsdb) don't close connection active, so client stucks when calling `body(response)`. 

The rfc2616 also don't demand that server must close connection active when request with header "Connection: close".
[http://www.ietf.org/rfc/rfc2616.txt](url)
_8.1.2.1 Negotiation

   An HTTP/1.1 server MAY assume that a HTTP/1.1 client intends to
   maintain a persistent connection unless a Connection header including
   the connection-token "close" was sent in the request. **If the server
   chooses to close the connection immediately after sending the
   response, it SHOULD send a Connection header including the
   connection-token close**._

Can we add active close for http client when response finished?

**Comment by deanberris** [comment]
Yes, I'd be happy to review an client option that will allow for client-side forced close. Do you mind sending a pull request for that @chenzhaoyu?

**Comment by chenzhaoyu** [comment]
Hi,@deanberris, you can check this PR #712 , thanks~
