### ISSUE TITLE
builder.hpp asio/ip/address.hpp No such file or directory

### ISSUE THREAD

**Issue by daviddoria** [cpp-netlib/cpp-netlib#715]
(I'm building with Boost 1.61 and cpp-netlib 0.12)

I built cpp-netlib successfully by simply specifying `BOOST_ROOT=/path/to/my/boost` when running CMake. However, I then followed the instructions for using cpp-netlib in my project by using:

```
set ( CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} /home/doria/build/cpp-netlib-0.12.0)
find_package ( cppnetlib 0.11.0 REQUIRED )

include_directories(${CPPNETLIB_INCLUDE_DIRS})

ADD_EXECUTABLE(MyProject MyProject.cpp)
target_link_libraries(MyProject ${CPPNETLIB_LIBRARIES})

```

but when I build my project I get:

> builder.hpp: asio/ip/address.hpp: No such file or directory

Any suggestions?

**Comment by glynos** [comment]
We don't recommend using cpp-netlib 0.12. I am going to prepare a release of 0.13 shortly which won't have the problem you describe.

**Comment by carun** [comment]
This doesn't happen anymore on 0.13-release branch. Can we close this issue?

**Comment by daviddoria** [comment]
Fine with me.

**Comment by carun** [comment]
@deanberris @glynos can you close this please?

**Comment by deanberris** [comment]
This is just waiting for a final release 0.13.0, but we can close this now. Thanks @carun!
