### ISSUE TITLE
cpp-netlib 0.13 cxxopts.hpp no such file or directory

### ISSUE THREAD

**Issue by daviddoria** [cpp-netlib/cpp-netlib#717]
When building cpp-netlib 0.13, I get:

```
/home/doria/source/cpp-netlib-0.13-release/libs/network/example/http_client.cpp:18:23: fatal error: cxxopts.hpp: No such file or directory
 #include "cxxopts.hpp"
                       ^
compilation terminated.

```

**Comment by glynos** [comment]
You need to get update the submodules. Call `git submodule init` followed by `git submodule update` before trying again.

**Comment by daviddoria** [comment]
Also, I downloaded the branch from github using https://github.com/cpp-netlib/cpp-netlib/archive/0.13-release.zip , so at that point I don't have a git repository (I didn't clone), so things like 'git submodule init' don't work.

**Comment by glynos** [comment]
Unless you have the dependencies elsewhere on your system, downloading the zip archive won't work. I wouldn't recommend downloading a snapshot of a repo as a zip. Until now we haven't supported it.

When we prepare the release, the tests and dependencies will be included in the package.

I don't know why you need cpp-netlib as a zip (I think you're the first person who has said that they use this feature).

**Comment by daviddoria** [comment]
No reason in particular this time, it's just an option provided by github so I use it sometimes. It should definitely be explicitly mentioned that this is not supported, or even better would be to turn it off in github (I don't know if that's possible?)

One way that we DO use that type of zipped repository though is to use things as a CMake External Project.

**Comment by glynos** [comment]
We intend to re-organise the master branch anyway. The dependencies in the sub-modules are pretty much only for the tests and samples. As you say, a check in the CMakeLists.txt file could be enough to simply warn the user that they're not available.

**Comment by belalshehab** [comment]
Hello, Glynos,
I'm getting the same error, while I'm using git submodule and I updated it.
any solution?
