### ISSUE TITLE
Default http server connection buffer size

### ISSUE THREAD

**Issue by carun** [cpp-netlib/cpp-netlib#726]
I am on branch 0.1.13-release.
I see that the default `BOOST_NETWORK_HTTP_SERVER_CONNECTION_BUFFER_SIZE` is [1024 bytes](https://github.com/cpp-netlib/cpp-netlib/blob/0.13-release/boost/network/protocol/http/server/async_connection.hpp#L59).

I did some tests (by uploading 250 MB of file) and I see that setting it to 8192 bytes increases the transfer rate by 7 folds. With 4096, the transfer rate is increased by close to 5 folds. The test code is in [here](https://github.com/carun/cpp-netlib/blob/example-async-file-uploader/libs/network/example/http/async_server_file_upload.cpp)

Can we increase the default value of `BOOST_NETWORK_HTTP_SERVER_CONNECTION_BUFFER_SIZE` to 8192 bytes or may be 4096 bytes (for memory constrained systems)? (Few KB's shouldn't matter, I guess).

**Comment by carun** [comment]
@deanberris Can you please suggest?

**Comment by deanberris** [comment]
I thought I responded to this but I can see that I hadn't. ☹️

I'm fine with increasing the default. I'd also consider making this a value that's configurable through the HTTP server options, and use the macro to define the default.

Happy to review a pull request that changes it to 4K to begin with.

Thanks @carun for the testing and suggestion!

**Comment by carun** [comment]
PR on the way. hg user here. Banging my head against this damn git CLI! git reset is probably the worst command in the history of computing. :(
