### ISSUE TITLE
boost 1.63 and optional incompatibilities

### ISSUE THREAD

**Issue by theopolis** [cpp-netlib/cpp-netlib#730]
Hi all, just wanted to make a quick-mention that package maintainers were encountering some compile issues with `boost` 1.63 and `cpp-netlib` (I think).

Details here: https://github.com/facebook/osquery/issues/2888

Seems like the `::optional` APIs changed in 1.63. If this is not on anyone's radar, totally cool. If it is an issue it's not high-pri.

**Comment by deanberris** [comment]
@glynos might know more, this is on the URI code path (amongst other places).

**Comment by maddanio** [comment]
is this fixed then?

**Comment by theopolis** [comment]
Sorry, yes, it was fixed with additional boost build flags!

**Comment by maddanio** [comment]
hey, so I need to build boost specially to make it work? I.e. it will not work "out of the box" with standard installations?

**Comment by deanberris** [comment]
@maddanio -- have you tried?

**Comment by maddanio** [comment]
builds and passes tests with homebrew's boost 1.64 on my mac on both 0.13 and master
