### ISSUE TITLE
documentation: example hello world server does not compile

### ISSUE THREAD

**Issue by maximiliankaul** [cpp-netlib/cpp-netlib#735]
Hi,
the example at `cpp-netlib/libs/network/example/http/hello_world_server.cpp` works nicely, but the one at [the online doc](http://cpp-netlib.org/0.12.0/examples/http/hello_world_server.html) does not compile. It fails to find `boost::network::http::server<T>::response`. It looks like the doc was updated on git but not on the website.
I’m using version `0.12.0-1` on Arch Linux.
Cheers

**Comment by deanberris** [comment]
Ah, good point. I think we just forgot to re-generate the documentation pages.

@glynos -- do you have time to try and regenerate+update the website static pages?

**Comment by glynos** [comment]
Not for the next couple of weeks, sorry.

**Comment by virtulis** [comment]
Bump. Are the docs still out of date or am I looking at the wrong docs somehow? :)

**Comment by deanberris** [comment]
Let me see whether I can get to it this week. Apologies for the delay here @virtulis -- I owe users a 0.13 release and progress on some of the more pressing design/implementation issues for a 1.0 release.

**Comment by deanberris** [comment]
I've not re-generated the 0.12.0 docs, but the 0.13.0 beta is now up.

Closing this out, unless there's something else we need to do here?
