### ISSUE TITLE
Does this require any other dependencies?

### ISSUE THREAD

**Issue by AraHaan** [cpp-netlib/cpp-netlib#736]
Like curlpp, does this require any other dependencies or can I build this from scratch using the Developer Command Prompt that comes from Visual Studio 2015 so I can invoke cl.exe directly to avoid things like linking the C Runtime Library that I do not like for it to use so things like this can work on versions of Windows before windows Vista and 7. Basically I like to target pretty much about all versions of Windows with just 1 build (Unless the user is using Windows 3.1).

Not only that but I want to make it easy do compile with my own libraries for an API that takes in json formatted requests for every endpoint. (I want to compile this inside of my library so that way I can easily update everything if I need. Sadly not sure if I would have to find my own websocket stuff that supports zlib compression/decompression of some resonses/requests though.

**Comment by deanberris** [comment]
We document the dependencies and requirements at http://cpp-netlib.org/0.12.0/getting_started.html. If you need SSL support, we depend on openssl (or what Boost.Asio allows you to depend on). We also depend on Boost.

I know some users statically link in cpp-netlib and openssl. Your mileage may vary though.
