### ISSUE TITLE
When cpp-netlib is using the latest openssl, crash occurs.

### ISSUE THREAD

**Issue by qwedsazzcc** [cpp-netlib/cpp-netlib#739]
When a Windows program is using cpp-netlib release 1.3 and openssl 1.02j or 1.02k for stress testing, if 500 https requests for stress testing is reached within 1 second, the program will crash after about half an hour. The crash occurs in line 188 of openssl-1.0.2k\crypto\lhash\lhash.c. This problem is not recurred in openssl 1.02 i.
======= Backtrace: =========
>	PortGatewayServer.exe!lh_insert(lhash_st * lh, void * data) Line 188	C
 	PortGatewayServer.exe!CRYPTO_dbg_malloc(void * addr, int num, const char * file, int line, int before_p) Line 527	C
 	PortGatewayServer.exe!CRYPTO_malloc(int num, const char * file, int line) Line 354	C
 	PortGatewayServer.exe!BUF_MEM_new() Line 75	C
 	PortGatewayServer.exe!mem_new(bio_st * bi) Line 123	C
 	PortGatewayServer.exe!BIO_set(bio_st * bio, bio_method_st * method) Line 100	C
 	PortGatewayServer.exe!BIO_new(bio_method_st * method) Line 75	C
 	PortGatewayServer.exe!ssl3_init_finished_mac(ssl_st * s) Line 567	C
 	PortGatewayServer.exe!ssl23_accept(ssl_st * s) Line 201	C
 	PortGatewayServer.exe!boost::asio::ssl::detail::engine::do_accept(void * __formal, unsigned __int64 __formal) Line 292	C++
 	PortGatewayServer.exe!boost::asio::ssl::detail::engine::perform(int(boost::asio::ssl::detail::engine::*)(void *, unsigned __int64) op, void * data, unsigned __int64 length, boost::system::error_code & ec, unsigned __int64 * bytes_transferred) Line 241	C++
 	PortGatewayServer.exe!boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::ssl::detail::handshake_op,<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> >::operator()(boost::system::error_code ec, unsigned __int64 bytes_transferred, int start) Line 140	C++
 	PortGatewayServer.exe!boost::asio::ssl::detail::async_io<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::ssl::detail::handshake_op,<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> >(boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> > & next_layer, boost::asio::ssl::detail::stream_core & core, const boost::asio::ssl::detail::handshake_op & op, boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::read_more::__l5::<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> & handler) Line 337	C++
 	PortGatewayServer.exe!boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::async_handshake<<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> & __ptr64>(boost::asio::ssl::stream_base::handshake_type type, boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::read_more::__l5::<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> & handler) Line 455	C++
 	PortGatewayServer.exe!boost::network::stream_handler::async_handshake<<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> >(boost::asio::ssl::stream_base::handshake_type handler, boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::read_more::__l5::<lambda_bed0ce9d30dd71b15a6b37f19a3d8386> &&) Line 160	C++
 	PortGatewayServer.exe!boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::read_more(boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::state_t state) Line 483	C++
 	PortGatewayServer.exe!boost::network::http::async_connection<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::start() Line 475	C++
 	PortGatewayServer.exe!boost::network::http::async_server_base<boost::network::http::tags::http_server,netlib::NetLibAsyncServer>::handle_accept(const boost::system::error_code &) Line 152	C++
 	PortGatewayServer.exe!boost::asio::detail::win_iocp_socket_accept_op<boost::asio::basic_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::ip::tcp,<lambda_9d5341a6c5fafd231a378bb175e1c8a3> >::do_complete(boost::asio::detail::win_iocp_io_service * owner, boost::asio::detail::win_iocp_operation * base, const boost::system::error_code & result_ec, unsigned __int64 __formal) Line 142	C++
 	PortGatewayServer.exe!boost::asio::detail::win_iocp_io_service::do_one(bool ec, boost::system::error_code &) Line 406	C++
 	PortGatewayServer.exe!boost::asio::detail::win_iocp_io_service::run(boost::system::error_code & ec) Line 164	C++
 	PortGatewayServer.exe!boost::asio::io_service::run() Line 60	C++
 	PortGatewayServer.exe!netlib::detail::NetLibAsyncServerImpl::start() Line 392	C++
 	PortGatewayServer.exe!boost::_bi::list2<boost::_bi::value<netlib::NetLibAsyncServer * __ptr64>,boost::_bi::value<std::shared_ptr<netlib::Settings> > >::operator()<boost::_mfi::mf1<void,netlib::NetLibAsyncServer,std::shared_ptr<netlib::Settings const > const & __ptr64>,boost::_bi::list0>(boost::_bi::type<void> f, boost::_mfi::mf1<void,netlib::NetLibAsyncServer,std::shared_ptr<netlib::Settings const > const &> &) Line 319	C++
 	PortGatewayServer.exe!boost::detail::thread_data<boost::_bi::bind_t<void,boost::_mfi::mf1<void,netlib::NetLibAsyncServer,std::shared_ptr<netlib::Settings const > const & __ptr64>,boost::_bi::list2<boost::_bi::value<netlib::NetLibAsyncServer * __ptr64>,boost::_bi::value<std::shared_ptr<netlib::Settings> > > > >::run() Line 117	C++
 	[External Code]	
 	PortGatewayServer.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	[External Code]

**Comment by deanberris** [comment]
Thanks for the report -- unfortunately I don't think this is a cpp-netlib bug, if this doesn't reproduce with a different version of openssl.
