### ISSUE TITLE
I have error for first test with cpp-netlib :: using visual studio 2015

### ISSUE THREAD

**Issue by Mohammedyasein** [cpp-netlib/cpp-netlib#744]
hey there 

iam using visual studio 2015

cannot open include file: 'asio/ip/address.hpp' directory  

note : i use boost asio .org and i use cpp-netlib 

pleas any help

**Comment by deanberris** [comment]
0.12.0 requires non-boost asio. Please use the standalone asio instead.

Alternatively, you can use the latest from the 0.13-release branch and see if that works for you.
