### ISSUE TITLE
error: comparison between signed and unsigned

### ISSUE THREAD

**Issue by ekigwana** [cpp-netlib/cpp-netlib#747]
master @ commit 21624f21377dc37c478e85142226103b6b2389b0

cpp-netlib/boost/network/protocol/http/client/connection/async_protocol_handler.hpp:353:42: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

`---    return this->partial_parsed.length() >= this-> content_length;`
`+++    return static_cast<long long>(this->partial_parsed.length()) >= this->content_length;`

**Comment by deanberris** [comment]
Thanks for the report @ekigwana -- do you mind sending a pull request to fix this? Also, I would suggest using `std::ssize_t` instead of `long long`.

**Comment by ekigwana** [comment]
Done
