### ISSUE TITLE
Exception when running async_server

### ISSUE THREAD

**Issue by carun** [cpp-netlib/cpp-netlib#748]
We observed this error in our app. I have not figured the root cause. This is definitely _not_ caused by load as I can see that the transactions are less frequent.

```
terminate called after throwing an instance of
'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
what():  remote_endpoint: Bad file descriptor
```

**Comment by deanberris** [comment]
Hi @carun -- can you provide details, like what version of Boost you're using, what version of cpp-netlib, using what compiler? Also, if you can provide a means of reproducing it, it will increase the chances for actually getting it fixed.

**Comment by carun** [comment]
Hi @deanberris, the issue happened on production box (running on docker) to which we don't have any access. I'm unable to reproduce it locally. I'll update if I manage to reproduce it.

OS: Ubuntu 16.04 (64 bit).
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
We use Boost (1.58) and cpp-netlib (0.11.2) are packed with the distro. So we don't custom build against the latest versions.

**Comment by deanberris** [comment]
Thanks @carun -- while I'm happy to see whether we can patch 0.11-devel (if users actually require this version, then it still makes sense to support it longer term) it may be that we'd need to find a few volunteers to back-port fixes to bugs from newer versions back to 0.11-devel. I currently do not have time to do this myself, but I'm still happy to do code reviews if you (or someone else) were willing to do some of it.

**Comment by carun** [comment]
@deanberris Sure. I will keep you posted in any case. Thanks for your help.

**Comment by carun** [comment]
This doesn't happen on `0.13-release` branch, so closing the issue.
