### ISSUE TITLE
CMake fails on Ubuntu Server

### ISSUE THREAD

**Issue by sharyxx** [cpp-netlib/cpp-netlib#761]
Running Cmake with default recommended parameters 
`
>$ mkdir ~/cpp-netlib-build
>$ cd ~/cpp-netlib-build
>$ cmake -DCMAKE_BUILD_TYPE=Debug \
> -DCMAKE_C_COMPILER=gcc   \
>-DCMAKE_CXX_COMPILER=g++ \
>  ~/cpp-netlib

>ERROR: cmake build fails with following message

>CMake Error at CmakeLists.txt:136 (add_subdirectory):
>The source directory

>/root/cpp-netlib/deps/googletest

>does not contain a CMakeLists.txt file.

>CMake Error at CmakeLists.txt:136 (add_subdirectory):
 >add_subdirectory given source "deps/uri/test" which is not an existing directory.

> --Configuration incomplete, errors occurred!
`
I had been trying to build this but it seems like I am missing some subdirectories. I pulled the original source from git. Hope someone can help me with this.

**Comment by glynos** [comment]
Try running the following from the command line before running CMake:

git submodule update --init --recursive

**Comment by sharyxx** [comment]
Thanks. It solved the error
