### ISSUE TITLE
Cmake Fails

### ISSUE THREAD

**Issue by xinthose** [cpp-netlib/cpp-netlib#790]
Hello.  I am trying to cmake the latest version and get the following errors:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:116 (add_subdirectory):
  The source directory

    /home/adam/Downloads/cpp-netlib/deps/uri

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:135 (add_subdirectory):
  The source directory

    /home/adam/Downloads/cpp-netlib/deps/googletest

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:136 (add_subdirectory):
  add_subdirectory given source "deps/uri/test" which is not an existing
  directory.


-- Configuring incomplete, errors occurred!
```
I am not trying to build it with SSL.
Thank you.

**Comment by deanberris** [comment]
You should be able to do this by setting the `CPP-NETLIB_ENABLE_HTTPS` option to "Off" either through the cmake invocation:

```
cmake -DCPP-NETLIB_ENABLE_HTTPS=Off ...
```

(The option is defined in https://github.com/cpp-netlib/cpp-netlib/blob/master/CMakeLists.txt#L13).

Or when configuring using `ccmake`.

I notice that you also hadn't updated the submodules the project needs to build. Our documentation points out the best way of getting the development version of the library:

https://github.com/cpp-netlib/cpp-netlib#downloading-cpp-netlib

```
$ git clone https://github.com/cpp-netlib/cpp-netlib
$ cd cpp-netlib
$ git submodule init
$ git submodule update
```

I hope this helps!
