### ISSUE TITLE
build fails with gcc 7.2

### ISSUE THREAD

**Issue by tex** [cpp-netlib/cpp-netlib#796]
Branch 0.13-release.
GCC 6.4 compiles without any problems or warnings. Boost 1.65.

Looks like something between optional and uri...

include/boost/optional/optional.hpp:964:5: error: no type named ‘type’ in ‘struct boost::enable_if<boost::is_same<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > >, std::optional<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > > > >, boost::optional<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > > >&>’
/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/detail/uri_parts.hpp: In instantiation of ‘void boost::network::uri::detail::uri_parts<FwdIter>::update() [with FwdIter = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’:
/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/uri.hpp:206:23:   required from here
include/boost/optional/optional.hpp:994:15: note: candidate: boost::optional<T>& boost::optional<T>::operator=(boost::none_t) [with T = boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > >]
include/boost/optional/optional.hpp:994:15: note:   no known conversion for argument 1 from ‘std::optional<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > > >’ to ‘boost::none_t’
In file included from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/uri.hpp:15:0,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/impl/request.hpp:32,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/request.hpp:10,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/client.hpp:11,
                 from /home/milan/dev/cpp/wc/main.cpp:2:

/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/detail/uri_parts.hpp: In instantiation of ‘void boost::network::uri::detail::hierarchical_part<FwdIter>::update() [with FwdIter = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’:
/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/detail/uri_parts.hpp:70:5:   required from ‘void boost::network::uri::detail::uri_parts<FwdIter>::update() [with FwdIter = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’
/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/uri.hpp:206:23:   required from here
/home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/uri/detail/uri_parts.hpp:32:19: error: no match for ‘operator=’ (operand types are ‘boost::optional<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > > >’ and ‘std::optional<boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > > >’)
         user_info = make_optional(iterator_range<FwdIter>(std::begin(host.get()),
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             std::begin(host.get())));
                                             ~~~~~~~~~~~~~~~~~~~~~~~~
In file included from include/boost/optional.hpp:15:0,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/message/async_message.hpp:13,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/impl/request.hpp:26,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/request.hpp:10,
                 from /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/client.hpp:11,
                 from /home/milan/dev/cpp/wc/main.cpp:2:

**Comment by anonimal** [comment]
>0.13-release

I cannot reproduce with gcc 7.3.0 and boost 1.66.

**Comment by tex** [comment]
Good :)
