### ISSUE TITLE
Where to get the type of Request method(GET, PUT, POST) from? 

### ISSUE THREAD

**Issue by katemamba** [cpp-netlib/cpp-netlib#811]
I have a normal async server from examples running and I want to configure different handlers for different endpoints. Once the server is running on localhost:8000 , based on its uri endpoints, different functions are called.
This is a sample code within operator method()
 `  void operator()(server::request const& request,
                  server::connection_ptr connection){...
         
std::cout<<request.destination<<std::endl;
        if(request.destination=="/user"){
            HandleUserlogin lc;
             lc.handle("hello","world");
         data = request.destination;
        connection->write(data);
    }`

Here I am able to distinguish between endpoints using request.destination. What is the correct approach to find out the Method by which request is sent (like GET, POST, PUT, DELETE), so i have different handlers on same endpoint in place?

**Comment by carun** [comment]
You can use `req.method`

```cpp
if (req.destination == "/user") {
    if (req.method == "GET") {
        doGet();
    }
    else if (req.method == "POST") {
        doPost();
    }
}

Appreciate if you can close the issue.

**Comment by katemamba** [comment]
Thanks @carun
