### ISSUE TITLE
Generate session token or unique id for Post response

### ISSUE THREAD

**Issue by katemamba** [cpp-netlib/cpp-netlib#821]
What needs to be done in server, if a POST call expects an id/session token to be generated as response?

I want the server Post to respond with a unique id, everytime someone logs in[http://localhost:8000/login], and response body to contain {"id":"sadqwe23sdwqe"}.

**Comment by carun** [comment]
@katemamba Look at the examples and don't open issues for such questions.

**Comment by katemamba** [comment]
@carun Sorry for trouble,can you point me to a file that has this? 
I have searched through examples and found the generation in form of connection write.
`std::string data= generateST()
connection.write(data.str());`
and data can generate id/session token. 
What my issue here is , is there a way to check that the session token exists and is unique per user by the server/cppnetlib itself, or the method should handle it explicitly?

**Comment by carun** [comment]
These are application specific (so called web-app) implementations. cpp-netlib is a pure HTTP server and doesn't do this by itself.

Look into https://github.com/cpp-netlib/cpp-netlib/blob/0.13-release/libs/network/example/http/fileserver.cpp

You can implement a similar handler for user sessions, DB, etc.
