### ISSUE TITLE
compile failed on ubuntu 

### ISSUE THREAD

**Issue by Triswuting** [cpp-netlib/cpp-netlib#825]
. build.sh 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.66.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build
/usr/bin/cmake -H/home/tingwu/Downloads/cpp-netlib-0.12.0-final -B/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/CMakeFiles /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
make -f libs/network/src/CMakeFiles/cppnetlib-uri.dir/build.make libs/network/src/CMakeFiles/cppnetlib-uri.dir/depend
make -f libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/build.make libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/depend
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tingwu/Downloads/cpp-netlib-0.12.0-final /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tingwu/Downloads/cpp-netlib-0.12.0-final /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src/CMakeFiles/cppnetlib-uri.dir/DependInfo.cmake --color=
Scanning dependencies of target cppnetlib-client-connections
Scanning dependencies of target cppnetlib-uri
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
make -f libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/build.make libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/build
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
[  1%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/client.cpp.o
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/c++   -DASIO_HEADER_ONLY -DBOOST_SPIRIT_THREADSAFE -DBOOST_TEST_DYN_LINK -I/usr/local/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final/deps/asio/asio/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final  -std=c++11 -Wall -std=c++11   -o CMakeFiles/cppnetlib-client-connections.dir/client.cpp.o -c /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src/client.cpp
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
make -f libs/network/src/CMakeFiles/cppnetlib-uri.dir/build.make libs/network/src/CMakeFiles/cppnetlib-uri.dir/build
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
[  2%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/c++   -DASIO_HEADER_ONLY -DBOOST_SPIRIT_THREADSAFE -DBOOST_TEST_DYN_LINK -I/usr/local/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final/deps/asio/asio/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final  -std=c++11 -Wall -std=c++11   -o CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o -c /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src/uri/uri.cpp
[  4%] Linking CXX static library libcppnetlib-client-connections.a
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/cmake -P CMakeFiles/cppnetlib-client-connections.dir/cmake_clean_target.cmake
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/cppnetlib-client-connections.dir/link.txt --verbose=1
/usr/bin/ar qc libcppnetlib-client-connections.a  CMakeFiles/cppnetlib-client-connections.dir/client.cpp.o
/usr/bin/ranlib libcppnetlib-client-connections.a
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
[  4%] Built target cppnetlib-client-connections
make -f libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/build.make libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/depend
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tingwu/Downloads/cpp-netlib-0.12.0-final /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/DependInfo.cmake --color=
Scanning dependencies of target cppnetlib-server-parsers
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
make -f libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/build.make libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/build
make[2]: Entering directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
[  5%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/server_request_parsers_impl.cpp.o
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/c++   -DASIO_HEADER_ONLY -DBOOST_SPIRIT_THREADSAFE -DBOOST_TEST_DYN_LINK -I/usr/local/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final/deps/asio/asio/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final  -std=c++11 -Wall -std=c++11   -o CMakeFiles/cppnetlib-server-parsers.dir/server_request_parsers_impl.cpp.o -c /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src/server_request_parsers_impl.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/build.make:65: recipe for target 'libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/server_request_parsers_impl.cpp.o' failed
make[2]: *** [libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/server_request_parsers_impl.cpp.o] Error 4
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
CMakeFiles/Makefile2:166: recipe for target 'libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/all' failed
make[1]: *** [libs/network/src/CMakeFiles/cppnetlib-server-parsers.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-uri.dir/uri/schemes.cpp.o
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/c++   -DASIO_HEADER_ONLY -DBOOST_SPIRIT_THREADSAFE -DBOOST_TEST_DYN_LINK -I/usr/local/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final/deps/asio/asio/include -I/home/tingwu/Downloads/cpp-netlib-0.12.0-final  -std=c++11 -Wall -std=c++11   -o CMakeFiles/cppnetlib-uri.dir/uri/schemes.cpp.o -c /home/tingwu/Downloads/cpp-netlib-0.12.0-final/libs/network/src/uri/schemes.cpp
[  8%] Linking CXX static library libcppnetlib-uri.a
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/cmake -P CMakeFiles/cppnetlib-uri.dir/cmake_clean_target.cmake
cd /home/tingwu/Downloads/cpp-netlib-0.12.0-final/build/libs/network/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/cppnetlib-uri.dir/link.txt --verbose=1
/usr/bin/ar qc libcppnetlib-uri.a  CMakeFiles/cppnetlib-uri.dir/uri/uri.cpp.o CMakeFiles/cppnetlib-uri.dir/uri/schemes.cpp.o
/usr/bin/ranlib libcppnetlib-uri.a
make[2]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
[  8%] Built target cppnetlib-uri
make[1]: Leaving directory '/home/tingwu/Downloads/cpp-netlib-0.12.0-final/build'
Makefile:141: recipe for target 'all' failed
make: *** [all] Error 2

please help to figure out why and compile succesfully

**Comment by os12** [comment]
I'd guess your VM is short on memory and the kernel killed `gcc`.

**Comment by anonimal** [comment]
@Triswuting This isn't a cpp-netlib issue. Build with more memory/swap space or try building with clang.

**Comment by deanberris** [comment]
I agree. Closing now.
