### ISSUE TITLE
Error in make - Linux debian x86_64 

### ISSUE THREAD

**Issue by sridhareee1** [cpp-netlib/cpp-netlib#831]
Installed boost version : boost_1_66_0
Installed openssl version: OpenSSL 1.1.1-pre3-dev 
command used for cmake in build directory:
"cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ../cpp-netlib"

Error in make:
/usr/local/include/boost/asio/ssl/detail/impl/engine.ipp:221:9: error: ‘SSL_R_SHORT_READ’ was not declared in this scope
         ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ),

**Comment by deanberris** [comment]
I don't think this is an issue with cpp-netlib, as it seems to be an issue with Boost.Asio not being able to find that macro definition. My suggestion here would be to ensure that CMake is able to find the correct OpenSSL installation. If it persists, I suspect asking the Boost.Asio maintainers about this would be the most prudent course of action.

**Comment by sridhareee1** [comment]
Thanks for the input. I'll check the Makefile and OpenSSL.
