### ISSUE TITLE
unit test faild,because of "http://www.boost.org" return "301 Moved Permanently"

### ISSUE THREAD

**Issue by limenghua** [cpp-netlib/cpp-netlib#836]
OS: CentOS7.4 x64
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
boost 1.66
cpp-netlib:0.12.0-final

tests]$ ./cpp-netlib-http-client_get_streaming_test
cpp-netlib-0.12.0-final/libs/network/test/http/client_get_streaming_test.cpp:41: Failure
Expected: 200u
      Which is: 200
To be equal to: response.status()
      Which is: 301
/home/limenghua/Downloads/cpp-netlib-0.12.0-final/libs/network/test/http/client_get_streaming_test.cpp:42: Failure
      Expected: "OK"
To be equal to: response.status_message()
      Which is: "Moved Permanently"

**Comment by umennel** [comment]
Hi @limenghua, we used to connect to boost.org in some of the tests because the site would support chunked transfer encoding. But now they don't allow unencrypted connections any more. We need to find another source for testing chunked transfer encoding.

**Comment by deanberris** [comment]
Yeah, this one's tricky -- we definitely should update the test to either:

1) Use HTTPS and chunked transfer encoding.

2) Set up our own server to make HTTP requests to.

While I'm not a great fan of solution 2, that might be the easiest thing to do in this case.

**Comment by yhager** [comment]
The test passes for me on 0.13-release branch if I change http to https:
```patch
--- a/libs/network/test/http/client_get_streaming_test.cpp
+++ b/libs/network/test/http/client_get_streaming_test.cpp
@@ -26,7 +26,7 @@ struct body_handler {
 TYPED_TEST_CASE(HTTPClientTest, ClientTypes);
 
 TYPED_TEST(HTTPClientTest, GetStreamingTest) {
-  typename TypeParam::request request("http://www.boost.org");
+  typename TypeParam::request request("https://www.boost.org");
   typename TypeParam::response response;
   typename TypeParam::string_type body_string;
   typename TypeParam::string_type dummy_body;
```

**Comment by deanberris** [comment]
Cool -- can you send a pull request with that change @yhager?
