### ISSUE TITLE
Copy constructor fails

### ISSUE THREAD

**Issue by jean-m-cyr** [cpp-netlib/cpp-netlib#854]
```
network::uri u("http://google.com");
cerr << u.host() << '\n';
u = network::uri("http://microsoft.com");
cerr << u.host() << '\n';
```

yields:

```
google.com
microsoft.

```

**Comment by deanberris** [comment]
Hi @jean-m-cyr -- can you provide a bit more information?

* Which version of the library are you using?
* What compiler, on which platform?
* Build flags?

**Comment by jean-m-cyr** [comment]
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

Not sure how to determine netlib version... whatever hunter pulls and builds.

hunter_add_package(CppNetlibUri)

**Comment by jean-m-cyr** [comment]
Same result with g++ 6.4.0

**Comment by deanberris** [comment]
I don't know what 'hunter' is, so I couldn't tell just from that, but you should be able to look at the downloaded dependency and see whether it's a `git` repository or something else.

**Comment by jean-m-cyr** [comment]
My apologies. The package used is head code at https://github.com/hunter-packages/cpp-netlib.git, which is a fork of this repo. Unlike this one, it includes uri.
