### ISSUE TITLE
UserProjectAccountProblem - official download links on website broken

### ISSUE THREAD

**Issue by RedFlames** [cpp-netlib/cpp-netlib#904]
Hi guys, I was curious to take a look at this, but starting off with the Getting Started guide I was immediately met with this problem - the download links appear to be broken.

Of course I assume I can just download Github Releases (edit: nope, hadn't checked yet, but there are none lol), but I tried searching here and didn't see any issue referencing this, so maybe it wasn't reported yet, and idk if someone is aware or not?

Clicking on any of the Download links on the website https://cpp-netlib.org/ I am met with this:
```
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>
The project to be billed is associated with a closed billing account.
</Message>
</Error>
```

So I guess something happened to the billing of the google cloud storage behind the website? 😅

**Comment by deanberris** [comment]
Oh whoops, that's on me. Thanks for the report!

Let me look into this and see if I can point them to tags in GitHub instead.

**Comment by deanberris** [comment]
This should now be fixed. I've done the following:

- Create releases on GitHub from the tags indicating the 0.13.0-final and 0.12.0-final releases.
- Update the website to no longer refer to externally hosted files.

Thanks again for the report @RedFlames, please reopen if there are any issues.

Cheers
