### ISSUE TITLE
compile error: response has no member named 'body'

### ISSUE THREAD

**Issue by robdesbois** [cpp-netlib/cpp-netlib#99]
I'm unable to set the body of the server response after its construction:

```c++
typedef boost::network::http::server< http_request_handler > server;
void http_request_handler::operator()( const server::request& rq, server::response& rsp )
{
   rsp = server::response::stock_reply( server::response::ok );

   rsp.body = "hello world!";
   body(rsp, "hello world!");
   rsp << body("hello world!");
}
```
The 3 lines attempting to set the response body yield the following compilation errors respectively:

* `‘boost::network::http::sync_server_base<boost::network::http::tags::http_server, dedupe::manage::http_request_handler>::response’ has no member named ‘body’`
* `boost/network/message/directives.hpp:25:5: error: ‘struct boost::network::http::basic_response<boost::network::http::tags::http_server>’ has no member named ‘body’`
* `boost/network/message/directives.hpp:25:5: error: ‘struct boost::network::http::basic_response<boost::network::http::tags::http_server>’ has no member named ‘body’`

Running with cpp-netlib 0.9.3 and gcc 4.6.1 in C++0x mode.

**Comment by glynos** [comment]
Closing this because it's old, and the server response object has been replaced.
